### PR TITLE
#183 Solved

### PR DESCRIPTION
**Pull request by Vikashchou-dhary**
Now the cards of Agro Blogs in a row are of same size #183

### CODE REVIEW

**Comment by Vikashchou-dhary** [comment]
@Suchitra-Sahoo I have fixed the bug. please check and merge it to the main

**Comment by Suchitra-Sahoo** [comment]
Please resolve the conflicts

**Comment by Vikashchou-dhary** [comment]
I have resolved the conflicts

**Comment by Vikashchou-dhary** [comment]
@Suchitra-Sahoo please review my changes #222

**Comment by Vikashchou-dhary** [comment]
@Suchitra-Sahoo I have the resolved the conflicts. Please review it #222 
CORRECTED IMAGE:-
correction
correction1
correction2

**Comment by Vikashchou-dhary** [comment]
@Suchitra-Sahoo is there any more changes i need to make in this

**Comment by Suchitra-Sahoo** [comment]
This branch has conflicts. The issue is resolved now.

**Pull request closed without merging**
