### PR TITLE
Add horizontal scroller into blog section    #383

### PR DESCRIPTION
**Pull request by ujj654**
Hello PA,

Fixed issue no - #383

## Description

I changed into the style.css file and index.html file.

Before the blog section was not well arranged so i arranged the whole blog section very well.

Make the blog section horizontally scrollable,  which makes the website user friendly.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Can you demonstrate with the help of a video

**Comment by ujj654** [comment]
Demonstration video of the changes:- 


https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/81877649/ec1e713c-2c22-4743-87e8-78a0838f4e0c

**Comment by Suchitra-Sahoo** [comment]
I had to revert back your PR. Its not working
image
The card sizes are uneven also the arrow is not visible.

**Comment by ujj654** [comment]
should I work again on this for merging the PR ??

**Pull request merged**
