### PR TITLE
Added pest control blog

### PR DESCRIPTION
**Pull request by Sameeksha-12**
Added a pest control techniques blog

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Mention issue number and screenshot of changes made.

**Comment by Sameeksha-12** [comment]
issue no. 25 
Screenshot (1032)

**Comment by Suchitra-Sahoo** [comment]
Improve the styling of the card as it is not matching also write blog in another file and attach it.

**Comment by Sameeksha-12** [comment]
I changed the styling of the card and it looks like below. Should I write the blog in a seperate html file instead of the external link?
image

**Comment by Suchitra-Sahoo** [comment]
This branch has conflicts.

**Comment by Sameeksha-12** [comment]
I didn't merge the changes I made second time. I just wanted to confirm if
the design was okay. May I know why the pull request was closed?

**Pull request closed without merging**
