### PR TITLE
created blogs and we can add blogs dynamically

### PR DESCRIPTION
**Pull request by usharani222**
## Related Issue
BUG: change the blog content #427

## Description
Added JSON file which creates blog card automatically and also created own blogs to be displayed when we click on blog.
## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
add a video to demonstrate your changes

**Comment by Suchitra-Sahoo** [comment]
give access

**Comment by Suchitra-Sahoo** [comment]
Make a video how the website is working after your changes. Code part i'll see no need to include in video.

**Comment by Suchitra-Sahoo** [comment]
Are you working?

**Comment by usharani222** [comment]
agri.mp4
<https://drive.google.com/file/d/1484BvEtP5ANlRvdMu06f_nGeTdfvEZFW/view?usp=drive_web>

**Comment by Suchitra-Sahoo** [comment]
give access

**Comment by Suchitra-Sahoo** [comment]
As you mentioned in the issue to add a feature of adding blogs so it should happen through website itself.

**Comment by Suchitra-Sahoo** [comment]
Like user can't go to the code to add their blogs right

**Comment by usharani222** [comment]
Ok

**Comment by Suchitra-Sahoo** [comment]
Once you are done raise another PR

**Pull request closed without merging**
