### PR TITLE
Navbar changes

### LINKED ISSUE #1023: BUG: Navbar is not proper
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The login button in navbar is getting overlapped by the dark mode switch. 
Screenshot (1130)

In the Buy products page, when we scroll down the navbar items change their position resulting in misalignment

Screenshot (1131)

 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Archiesachin**
## Related Issue
closes #1023 

## Description
Changed the navbar style on all pages so that it does not get overflown. 

## Homepage
Screenshot (1136)

## Buy products section

Screenshot (1137)

## FAQ section 

Screenshot (1135)

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
image
AgriLearnNetwork and options of navbar are too close. There should be proper spacing.

**Comment by Archiesachin** [comment]
Can you please add level labels as well @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
it will be added in your final PR

**Comment by Archiesachin** [comment]
## This is how it looks normally
Screenshot (1138)



## This is the sticky version on the navbar


Screenshot (1137)

**Pull request merged**
