### PR TITLE
Card theam 

### PR DESCRIPTION
**Pull request by pandeyji711**
Hi @Suchitra-Sahoo, I’ve been working on the theme for this section and I believe it’s looking better now. From this theam the size shouldn’t be an issue because the content may vary. Please take a look when you get a chance. Also, I noticed that the h2 heading for the Agro blog isn’t aligned properly. Could you please check on this? Thanks!”
Screenshot 2024-05-13 210807

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/154527778/ab2e71b1-240a-4361-8efa-101797126d6c

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
This idea doesn't looks good. improve it and resolve confflicts.

**Comment by pandeyji711** [comment]
@Suchitra-Sahoo any idea mam!!

**Comment by pandeyji711** [comment]
@Suchitra-Sahoo  The logo seems to have disappeared **I have fixed it**,and I’ve reverted to the previous theme. Additionally, I’ve fixed another problem where the cursor wasn’t pointing with the card.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/154527778/2a2d2c3e-dbd6-4026-a088-91091c36e381

Screenshot 2024-05-13 234217

**Comment by pandeyji711** [comment]
pr fix #229

**Comment by pandeyji711** [comment]
@Suchitra-Sahoo please review and merge

**Pull request merged**
