### PR TITLE
#497 Updated with Multilingual support

### PR DESCRIPTION
**Pull request by Anjankumarkamalapur**
Implemented Multilingual support(using google translation)
solved #497
image

image

### CODE REVIEW

**Comment by Anjankumarkamalapur** [comment]
@Suchitra-Sahoo Done with my work once have a look. Thank You.

**Comment by Suchitra-Sahoo** [comment]
This is  not looking good some words are in english and some are in hindi. Also after conversion words are not making proper sense. Keep only indian languages. Also the language changing option should be designed properly.

**Comment by Anjankumarkamalapur** [comment]
Actually after changing to other language it may take 2sec to change whole
webpage with accurately.

**Comment by Suchitra-Sahoo** [comment]
Okay keep two language english and hindi. Take refrence from this website and try to replicate https://www.bighaat.com/hi

**Comment by Anjankumarkamalapur** [comment]
Ok sure by tomorrow morning I will be committing these changes

**Pull request closed without merging**
