### PR TITLE
Navbar of about page updated again

### LINKED ISSUE #545: Feat: Navbar Must be visible in Blog page as well
### Describe the feature

Currently The navbar is not present in the blog page, I wish to add it.

### Add ScreenShots

Screenshot 2024-05-29 103438

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by sau-mili**
## Related Issue
resolves #545 

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [] Bug fix
- [ x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ x] I have performed a self-review of my code
- [ x] I have read and followed the Contribution Guidelines.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
screenshot is not visible

**Comment by sau-mili** [comment]
Screenshot 2024-06-01 234713
check now please

**Comment by sau-mili** [comment]
Can you please give me a higher level on this? Given the number of revisions, and time it took?

**Comment by Suchitra-Sahoo** [comment]
@sau-mili the options of navbar and not linked to respective pages in blog page.

**Comment by sau-mili** [comment]
I will add that, please give me a level 2 on this

**Pull request merged**
