### PR TITLE
CROP YIELD CALCULATOR

### PR DESCRIPTION
**Pull request by Shivanipandey31**
A Crop Yield Calculator is a tool used to estimate the potential yield of a crop based on various factors that affect crop growth and productivity. It's a valuable resource for farmers, agricultural professionals, and researchers to predict and optimize crop yields, making informed decisions about planting, harvesting, and resource allocation.
It calculates the expected crop yield by taking crop type ,weather condition soil type as input ,management practices ,crop rotation ,area into consideration.

Changes I have made-
1. Added a Crop yield calculator 
2. Updated the front-end with a new section in the dashboard for the crop yield calculator.
3. Also updated the quick-links

Screenshot 2024-05-18 141830

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Can you create a seperate page for crop yeild calculator. So that the user gets redirected there when he clicks on this feature. Also add a video to demonstrate how this calcultaor works.

**Comment by Shivanipandey31** [comment]
Where should I add a tutorial video?

**Comment by Suchitra-Sahoo** [comment]
Here itself.

**Comment by Shivanipandey31** [comment]
Here is a Demonstration on how to use Crop Yield Calculator

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142419781/3516402d-c397-4ae0-9f24-c8423a308d1c

**Comment by Suchitra-Sahoo** [comment]
I had to revert back your pr as its not working
image

**Pull request merged**
