### PR TITLE
Image gallery

### PR DESCRIPTION
**Pull request by gupta-ritik**
finally image gallery is updated and i am trying to solve issue number #104 

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/127002992/6258768a-a06f-4676-89bd-fd5cbfe5b19d

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts

**Comment by Suchitra-Sahoo** [comment]
Pull all changes from origin

**Comment by gupta-ritik** [comment]
conflicts is reslove check it once

**Comment by Suchitra-Sahoo** [comment]
@gupta-ritik your image gallery is not working properly. Also the carousel of home page has shifted to left after your changes. I have attached a screenshot of it. Because of these issues I had to revert back your PR.
Screenshot 2024-05-14 081657

**Comment by gupta-ritik** [comment]
Now I am fixing the issue that occurs but now unable to push git.
Please give permission to resolve the issue.
In terminal command it showing " Permission to your repo is denied"

**Comment by gupta-ritik** [comment]
Give a chance to made once again

**Comment by Suchitra-Sahoo** [comment]
But I have not denied any permission. I think there is some issue on your side as other contributors are able to push there changes.

**Comment by gupta-ritik** [comment]
Ok, I'll look into it.

**Pull request merged**
