### PR TITLE
Added beautiful `cart` ui

### LINKED ISSUE #952: Feat: Update the cart ui
### Describe the feature

@Suchitra-Sahoo 

we can update cart ui

we can make anothter route `/cart` 
from this

### Add ScreenShots

image

to something like this

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

@Suchitra-Sahoo 

# please add level 3

Feat: Update the cart ui #952

close #952

## Description
[Please include a brief description of the changes or features added]

- added cart ui
- make it responsive 
- new route `/cart.html`

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

kindly please check this and merge it

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

kindly please add level

**Comment by Suchitra-Sahoo** [comment]
Even after merging no change is visible

**Comment by Suchitra-Sahoo** [comment]
Please check

**Comment by dhruv8433** [comment]
Can you please try to locate `/cart` path

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

I just created new route front end with responsive

**Comment by Suchitra-Sahoo** [comment]
create another PR

**Comment by dhruv8433** [comment]
ok

**Pull request merged**
