### PR TITLE
newsletter feature is added

### PR DESCRIPTION
**Pull request by Srujitha-Raghava**
## Related Issue
#482 

## Description
Hello PA,
I have introduced a new button named subscribe in the website which further navigates to another page for newsletter subscription,where users can get all the information through their mails. By capturing email addresses from interested individuals, brands can expand their audience reach and nurture leads through targeted email campaigns.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143430142/d778c8b9-0600-43f8-9496-a227ec56c052

Screenshot 2024-05-25 162817

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Srujitha-Raghava** [comment]
@Suchitra-Sahoo this branch has no conflicts,kindly please review it!

**Comment by Suchitra-Sahoo** [comment]
It is not looking good right now. Work a little more on it. You may refer other website to see how to positon the subscribe button and its working too.

**Comment by Srujitha-Raghava** [comment]
sure mam! I will try to modify that asap

**Comment by Srujitha-Raghava** [comment]
@Suchitra-Sahoo mam i've been  through many websites for reference,i am confused about how to do. Can you suggest any?

**Comment by Srujitha-Raghava** [comment]
Screenshot 2024-05-26 114902

@Suchitra-Sahoo How about this?

**Comment by Suchitra-Sahoo** [comment]
This one is nice. Keep button in green shade and attach in footer.

**Comment by Suchitra-Sahoo** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pinterest.com%2Fpin%2F572097958888170897%2F&psig=AOvVaw0cyyq5GBtdAqIApvWgmeJI&ust=1716909171278000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCNizzpuProYDFQAAAAAdAAAAABAE

**Pull request closed without merging**
