### PR TITLE
Navbar Responsiveness  #372

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
Issue : #372 
I did some changes in the styling of navbar and the header to make it responsive .

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/118350936/d5de2a94-2374-4572-9c7e-3ec78008fb85

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
There is still an issue in navbar as the contact option is not visible.

**Comment by Ayushmaanagarwal1211** [comment]
I will see

**Comment by Ayushmaanagarwal1211** [comment]
@Suchitra-Sahoo can you please check it again

**Comment by Suchitra-Sahoo** [comment]
Add the video if you have done the changes.

**Comment by Ayushmaanagarwal1211** [comment]
uploading just a minute

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/118350936/94e94ecc-cffe-4f4c-b30d-f29d9aa4cec3

**Pull request merged**
