### PR TITLE
Solved mode issue

### PR DESCRIPTION
**Pull request by Bhumika1312**
## Related Issue
Fixes: #823 

## Description
Added the dark mode button and fixed it to toggle properly.

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/115869626/9cf56b46-62fb-4d82-a78c-442070b01dce

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/115869626/18b62c1a-961f-47c8-bfba-4fc1ddce0340

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Bhumika1312** [comment]
@Suchitra-Sahoo Please review it I have solve the mode issue
Thank you

**Comment by Bhumika1312** [comment]
If it is correct please add level and label and also assign it to me
Thank you

**Comment by Suchitra-Sahoo** [comment]
image
Remove this black its not looking good. Keep it as it is as in light mode.In contact us remove this green part and keep some very light grey shade for dark mode.
image

**Comment by Suchitra-Sahoo** [comment]
Make these changes and then i'll change your level to some higher level.

**Comment by Suchitra-Sahoo** [comment]
Also add js code in script.js file not index.html

**Pull request merged**
