### PR TITLE
Contact-form-responsive

### PR DESCRIPTION
**Pull request by Che140401**
Here we gooooooooooooooo

Made web page font style standard
Screenshot 2024-05-11 152750

Well designed contact form
Screenshot 2024-05-11 153004

Responsive form

Screenshot 2024-05-11 153148

Alert form
Screenshot 2024-05-11 153322

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
What is your issue number?

**Comment by Che140401** [comment]
> What is your issue number?

#81

**Comment by Che140401** [comment]
> What is your issue number?

I have made the pull request

**Comment by Suchitra-Sahoo** [comment]
Please check the changes as after merging your PR I can see that the learn, sow and grow words are not visible in homepage.

**Comment by Che140401** [comment]
So what is next step i have to revert it or should close this issue to work

**Comment by Suchitra-Sahoo** [comment]
I have already reverted your merged PR. You can raise another PR by pulling all the new changes from origin.

**Pull request merged**
