### PR TITLE
Update grammatical errors in Readme.MD

### PR DESCRIPTION
**Pull request by anshumanmondal2006**
Necessary grammatical changes and other modifications to text in readme file

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Mention you issue number.

**Comment by anshumanmondal2006** [comment]
I directly sent a pull request without raising an issue about the readme #90 is the pull request number

**Comment by anshumanmondal2006** [comment]
> Mention you issue number.

I directly pinged a pull request with id no. #90 without raising an issue about the readme just made a few necessary changes. Do i have to raise an issue?

**Comment by Suchitra-Sahoo** [comment]
You need to wait for the issue to be assigned and then raise PR. Also someone is already working on readme.

**Pull request closed without merging**
