### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by sancharigandhi**
I have updated the CSS of the header navbar. issue #359

image

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts also mention the issue number.

**Comment by sancharigandhi** [comment]
Issue #359

**Comment by Suchitra-Sahoo** [comment]
That's a PR number, what's your issue number?

**Comment by Suchitra-Sahoo** [comment]
Make a video because the main issue was the text of about section was too small in mobile screens.

**Comment by sancharigandhi** [comment]
Issue #256 

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/140971159/d13d1d4a-1ef0-4c71-9b66-b7415449b59c

**Comment by sancharigandhi** [comment]
Ma'am, please add a label to this issue. issue #256

**Comment by Suchitra-Sahoo** [comment]
I merged you PR but its still not working.

**Comment by Suchitra-Sahoo** [comment]
So i had to revert it

**Pull request merged**
