### PR TITLE
Added logo in navbar

### PR DESCRIPTION
**Pull request by AnushkaJainFirst**
agri-6
Kindly review @Suchitra-Sahoo

### CODE REVIEW

**Comment by AnushkaJainFirst** [comment]
@Suchitra-Sahoo Plz add **level** label on this issue before merging

**Comment by Suchitra-Sahoo** [comment]
Make the logo and favicon of the website same. Both can't look different

**Comment by AnushkaJainFirst** [comment]
Ok @Suchitra-Sahoo

**Comment by AnushkaJainFirst** [comment]
I have made the favicon and logo same. Kindly review @Suchitra-Sahoo

**Comment by AnushkaJainFirst** [comment]
agri-7

**Comment by AnushkaJainFirst** [comment]
agri-8

**Comment by Suchitra-Sahoo** [comment]
@AnushkaJainFirst the home page has been updated. You can check the changes by the link of the website but I guess in your branch you have not yet pulled the changes from origin. So do that.

**Comment by AnushkaJainFirst** [comment]
agri-9
Done @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
@AnushkaJainFirst I had to revert back your PR because I can see that in the favicon your logo is barely visible. It will be better if you can re disgn it.

**Comment by AnushkaJainFirst** [comment]
@Suchitra-Sahoo....I have designed a new logo with better visibility and
created a PR for it.
PR no. is #244 and issue-no is #127
Attached the screenshot of it in the mail as well as PR. Kindly review!

Regards
Anushka Jain

**Pull request merged**
