### PR TITLE
Added popup for signin successful

### LINKED ISSUE #1210: Feat: Adding "Login successful" when user logs in
### Describe the feature

When User logs if a pop up comes , it would look good , and user will get ensured that login is successful

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Maana-Ajmera**
## Related Issue
fixes #1210 

## Description
When User signs in if a pop up comes , it would look good , and user will get ensured that signin is successful

## Type of PR

- [X] Feature enhancement

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/0dc9f8e0-9dca-4a01-befa-56c505753885

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts. Improve the pop up as currently it is unncessarily occupying so much space.

**Comment by Maana-Ajmera** [comment]
https://github.com/user-attachments/assets/ef4a855e-65d4-4509-b602-61f673754f91



@Suchitra-Sahoo I have modified it like this , please review it , and if further changes are required , do let me know.

**Comment by Suchitra-Sahoo** [comment]
Mention issue number. You have mentioned PR number.

**Comment by Maana-Ajmera** [comment]
> Mention issue number. You have mentioned PR number.

I have mentioned the issue number only , #1210 is my issue number and #1221 is my PR number

**Pull request merged**
