### PR TITLE
Addition of footer at blog page

### PR DESCRIPTION
**Pull request by Hemav009**
## Related Issue
#603 

## Description
Added footer on blog page

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

**
image
**
 check at this page
 
 https://hemav009.github.io/AgriLearnNetwork/
 

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
The footer should be same as in home page. I can see you have placed the quick links towards right

**Comment by Hemav009** [comment]
@Suchitra-Sahoo  updated

**Comment by Suchitra-Sahoo** [comment]
Some changes have been made in search bar. You can look for those through website link. Those are not reflecting in your branch.
image

**Comment by Hemav009** [comment]
ok will update soon

**Comment by Hemav009** [comment]
@Suchitra-Sahoo  updated

**Pull request merged**
