### PR TITLE
Fixed the Blog page and Home page Navbar Elements

### PR DESCRIPTION
**Pull request by deepak00944**
## Related Issue
None

## Description
As mentioned in issue #732 the elements of the blog navbar and home navbar are not correctly positioned. I have fixed that issue for both pages the supporting screenshots are attached below. Kindly review this and let me know if I can add more things. 

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
**BEFORE HOME PAGE**

Before the login button was not at its place which is now fixed.
Screenshot (601)

When we hover on login button the Register button was not clearly visible.
Screenshot (602)

**AFTER HOME PAGE**

Login button and Register button are now clearly visible.

Screenshot (599)

Screenshot (600)

**BEFORE BLOG PAGE**

Screenshot (605)

**AFTER BLOG PAGE**

Screenshot (604)

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
attach a video about how it behaves in mobile devices too. Like whether the hambergur menu option is coming or not?

**Comment by deepak00944** [comment]
The hamburger menu is visible on mobile devices too.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/119965267/52d0459a-b551-42a6-9b6d-e4dee3aa018c

**Comment by Suchitra-Sahoo** [comment]
It is looking like this. Please do the corrections
image

**Comment by deepak00944** [comment]
I have commented mine code please uncomment it then it will be fine.
Go to styles.css ->  search for (.navbar a) and uncomment  this 136 line (/* margin-right: 4rem; */)

@Suchitra-Sahoo You have not label this PR i won't get any marks for this kindly label it with at least "gssoc" and "level2", I would be happy if you label it with level 3.

**Comment by Suchitra-Sahoo** [comment]
I have reverted your PR so make another PR with all corrections so that i can merge it.

**Comment by Suchitra-Sahoo** [comment]
You will get your level tags once your PR is merged. So don't worry.

**Comment by deepak00944** [comment]
I have created a another PR #817 now in this there are some conflicts please comment the particular code to remove the conflicts.

**Pull request merged**
