### PR TITLE
Issue#69: Enhance cards to redirect to webpage upon clicking.

### PR DESCRIPTION
**Pull request by RanjanaShenoy**
In Agro Blogs section, instead of click on heading to redirect to respective page, I have improved it such that upon clicking on ('div') service box, redirection happens to respective blogs. 

AgriLearnNetwork_Issue69 (1)

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Mention your issue number

**Comment by Suchitra-Sahoo** [comment]
issue #69

**Comment by Suchitra-Sahoo** [comment]
@RanjanaShenoy Can you just check again about why the cards are not redirecting on clicking. Pull all the changes from origin and then look into create. If you are able to resolve it i'll add level 2 label.

**Comment by RanjanaShenoy** [comment]
@Suchitra-Sahoo Sure. Let me check it

**Comment by RanjanaShenoy** [comment]
Hi @Suchitra-Sahoo ,
I found that - even though the changes that I pushed (PR) is merged, it is not reflecting in the code. Like before redirection happens upon clicking the card title only.
Somebody might have not taken the latest changes during making their code changes & raising PR.

**Comment by RanjanaShenoy** [comment]
Created a new PR for this
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/pull/241

**Pull request merged**
