### PR TITLE
chatbot -- able to merge issue#11

### PR DESCRIPTION
**Pull request by kairveeehh**
i have fixed the issue by integrating the chatbot and made it functional as well with suggestions also 
@Suchitra-Sahoo  #10 
## please review and merge it 
Screenshot 2024-05-14 124944
Screenshot 2024-05-14 124914
Screenshot 2024-05-14 124907

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Can  you keep the design of the bot same. Just work on its functioning part so that I can answer better.

**Comment by kairveeehh** [comment]
> Can  you keep the design of the bot same. Just work on its functioning part so that I can answer better.

@Suchitra-Sahoo but bots are not made from scratch they use third party websites like botpress chatbase so I have chosen the best one and integrated them what else?? @Suchitra-Sahoo please let me know

**Comment by Suchitra-Sahoo** [comment]
Yes I know even the bot which has been recently updated by a contributor also used a 3rd party website. I guess chatlling so you may use the same to improve its functioning. Rest the design and colour is fine so need to change that.

**Comment by kairveeehh** [comment]
> Yes I know even the bot which has been recently updated by a contributor also used a 3rd party website. I guess chatlling so you may use the same to improve its functioning. Rest the design and colour is fine so need to change that.

But for that I'll need to have the authentication of the person who has used that bot so as to improve its functioning also there's not much we can improve in Third party websites ..can you please elaborate what do you want to improve?

**Comment by Suchitra-Sahoo** [comment]
Okay but can't you find issues in current bot and design you own bot using some third party website. That will allow you to decide colour and design of the bot.

**Comment by kairveeehh** [comment]
> Okay but can't you find issues in current bot and design you own bot using some third party website. That will allow you to decide colour and design of the bot.

@Suchitra-Sahoo I did that using chatbase as the website and it functions very fast so I chose it

**Pull request closed without merging**
