### PR TITLE
Made the 'Buy Products' page responsive for mobile-view

### PR DESCRIPTION
**Pull request by vishanurag**
## Related Issue
Fixes: #1223 

## Description
- I have made the 'Buy Products' page responsive for mobile-view.
- Now this page will look responsive in mobile-view also.
- Additionally, I also fixed a 'link' tag of 'head' element because it was not written properly and causing style issues.

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/73749135-5a78-4607-9bb3-cebb9438bc15

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

_Please review and merge my pull-request under GSSoC'24_

### CODE REVIEW

**Comment by vishanurag** [comment]
@Suchitra-Sahoo Please review and merge my pull-request under GSSoC'24

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts

**Comment by vishanurag** [comment]
@Suchitra-Sahoo I have resolved the merge conflicts. Please check

**Comment by vishanurag** [comment]
@Suchitra-Sahoo Please review and merge my pull-request under GSSoC'24

**Pull request merged**
