### PR TITLE
Add carousel for blogs

### PR DESCRIPTION
**Pull request by P-lavanya16**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
#754 

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ X] I have performed a self-review of my code
- [ X] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by P-lavanya16** [comment]
@Suchitra-Sahoo Please kindly review this and add labels accordingly!!

**Comment by Suchitra-Sahoo** [comment]
Please don't raise a PR before the issue is assigned from next time. Now that you have raised a PR you can attach a video to show your changes, if your idea seems suitable i'll assign you the issue and then merge this PR.

**Comment by Suchitra-Sahoo** [comment]
Screenshot is not visible

**Comment by P-lavanya16** [comment]
Screenshot (122)

**Comment by Suchitra-Sahoo** [comment]
Please don't before the issue is assigned. Also the carsosel idea is not looking suitable for blog section.

**Pull request closed without merging**
