### PR TITLE
Created Separate page for FAQ's section

### PR DESCRIPTION
**Pull request by vinay-reddy31**
## Related Issue
image

## Description
Added a separate page for FAQ's section and Back button to navigate to main page

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Related Questions can be added based on our wish

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Can you add a video so that i can't see the entire working of faq section and suggest you the changes

**Comment by vinay-reddy31** [comment]
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/139357392/eafc5486-f8a8-4b64-a7da-920e0fd8eb67

**Comment by Suchitra-Sahoo** [comment]
Instead of white background on top you can use some other colour. Keep the Back button towards left. You can use a arrow instead like in blog section. Also change the dark green background. I am adding an image for your refrence.
image

**Comment by Suchitra-Sahoo** [comment]
once you are done raise another PR

**Pull request closed without merging**
