### PR TITLE
Enhance FAQ Section with Accordion Feature

### PR DESCRIPTION
**Pull request by ishap11**
## Related Issue
This pull request addresses issue #530.

## Description
Added an accordion feature to the FAQ section to improve content organization and user experience.

## Type of PR
- [x] Feature enhancement

## Screenshots / videos (if applicable)
Screenshot 2024-05-31 113642
Screenshot 2024-05-31 113751

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by ishap11** [comment]
I have created a pull request for the changes I made. Kindly review it.
Thank you.

**Comment by ishap11** [comment]
Thankyou for the feedback. I'll update you soon.

**Comment by Suchitra-Sahoo** [comment]
You can create seperate FAQ page. Pull the recent changes and there you wiil find faq page so improve it.

**Comment by Suchitra-Sahoo** [comment]
Raise another PR once done

**Comment by ishap11** [comment]
yes sure

**Pull request closed without merging**
