### PR TITLE
feat:  Made scroll to top feature button sticky

### PR DESCRIPTION
**Pull request by reshamsai150**
closes: #343
I have made the scroll-to-top button sticky on the website 

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/164533685/f3dcb4b6-5f54-4154-b86c-b46934621b7e

### CODE REVIEW

**Comment by reshamsai150** [comment]
add the level label @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
add some screenshot or video to demonstrate your changes.

**Comment by reshamsai150** [comment]
Ok

**Comment by reshamsai150** [comment]
added video @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
Pull all the changes from origin

**Pull request closed without merging**
