### PR TITLE
Navbar updated on about page

### LINKED ISSUE #545: Feat: Navbar Must be visible in Blog page as well
### Describe the feature

Currently The navbar is not present in the blog page, I wish to add it.

### Add ScreenShots

Screenshot 2024-05-29 103438

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by sau-mili**
## Related Issue
resolves #545 

## Description
added the navbar on about page

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot 2024-05-31 033445
Screenshot 2024-05-31 033505

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
The back option should be on navbar. Also Agroblogs shouldn't have same design as navbar. Just simply write AgroBlogs

**Comment by sau-mili** [comment]
Sure, will update these changes soon

**Comment by sau-mili** [comment]
Screenshot 2024-05-31 211937
Please check now

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts

**Comment by sau-mili** [comment]
Please check now

**Comment by Suchitra-Sahoo** [comment]
recently login option has been added. So pull those changes

**Comment by sau-mili** [comment]
please check now . 
Screenshot 2024-06-01 175456


also a req, can you please consider higher level labels, the navbar enhancements in last pull and this one, required a lot of changes

**Comment by Suchitra-Sahoo** [comment]
Remove the arrow as clicking home option will take the user to home page. Keep the position of logo and all options at same place as in home page

**Comment by sau-mili** [comment]
But you asked me to add it yesterday.. you sure?

**Comment by Suchitra-Sahoo** [comment]
Might be a mistake from my side

**Pull request closed without merging**
