### PR TITLE
Background Video added in the about section issue #256

### PR DESCRIPTION
**Pull request by sancharigandhi**
I have added a video to the about section and made some UI changes to align it with the home page. The video file, 'Agriculturevideo.mp4,' has been placed in the root directory. 

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/140971159/e5461e37-a327-46fd-959e-68dc211aacb8

### CODE REVIEW

**Comment by sancharigandhi** [comment]
I have adjusted the brightness and contrast to increase the visibility of the background video.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/140971159/9f66c287-5971-40a6-af06-bdaf90250d5f

**Comment by Suchitra-Sahoo** [comment]
In website it looks good but in case of mobile screen the text is becoming too small. Previously it was not like that. Also there is a gap between the carousel and the about section video in case of mobile screen. So kindly look into it and do the required changes. Then i'll add your label.
image
image

**Comment by Suchitra-Sahoo** [comment]
issue #256

**Comment by sancharigandhi** [comment]
Surely mam!

**Pull request merged**
