### PR TITLE
Fix login page minor errors

### PR DESCRIPTION
**Pull request by justmirr**
## Related Issue
#1165 

## Description
I fixed the minor issues in login page which were making the UI look unattractive.
agrilearn

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
attach images of the sections after the changes are made

**Comment by justmirr** [comment]
already attached in screenshot/videos section

**Comment by Suchitra-Sahoo** [comment]
image
There is a gap between footer and carousel try to remove that.

**Comment by justmirr** [comment]
sure i'll fix that!

**Pull request merged**
