### PR TITLE
preloader 

### PR DESCRIPTION
**Pull request by solanki505**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description
#486

## Type of PR

- [x] Feature enhancement

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/158484284/8457e526-2c7a-47d9-a06b-b8a1aa711866

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Recently some changes have been made. Have you pulled those from origin?

**Comment by solanki505** [comment]
> Recently some changes have been made. Have you pulled those from origin?

Yes I forked from origin 15 min ago after deleting the previous repo from my account

**Comment by solanki505** [comment]
> Recently some changes have been made. Have you pulled those from origin?

Yes maam

**Comment by Suchitra-Sahoo** [comment]
Have you written the code of both style and javscript within html file? Seperate those as there are style.css and script.js file.

**Comment by solanki505** [comment]
> Have you written the code of both style and javscript within html file? Seperate those as there are style.css and script.js file.

ok making the changes

**Comment by solanki505** [comment]
> Have you written the code of both style and javscript within html file? Seperate those as there are style.css and script.js file.

@Suchitra-Sahoo Maam I made the changes

**Comment by Suchitra-Sahoo** [comment]
Reverted back your PR as your preloader is running even after the page is loaded. Also in mobile devices the loader keeps on running and the page is opened after a lot of time.

**Pull request merged**
