### PR TITLE
Added Scroll to Top feature

### LINKED ISSUE #806: Feat: Add Scroll to top in AgroBlogs
### Describe the feature

I want to add scroll to top button feature in agroblogs page.

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MuraliDharan7**
## Related Issue
- Closes #806 

## Description
added Scroll to top button feature in blogs page, which takes the user to the top of the page.

## Type of PR

- [X ] Feature enhancement

## Screenshots / videos (if applicable)
image

## Checklist:
- [X ] I have performed a self-review of my code
- [X ] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Make the scroll to top same as present in homepage.

**Comment by Suchitra-Sahoo** [comment]
attach screenshot

**Comment by MuraliDharan7** [comment]
Kindly Open this PR. I will Do the rest of the things in 1 day

**Comment by MuraliDharan7** [comment]
Home page already has this feature
image

Kindly check this.

**Comment by Suchitra-Sahoo** [comment]
but in issue you mentioned to add it in blog page

**Comment by MuraliDharan7** [comment]
I have already added in blog page. Kindly check this branch and the PR Code. 
Then You requested me to add it in home page as well.

**Comment by Suchitra-Sahoo** [comment]
Add a screenshot bcs in previous attached image the scroll to top feature was not same as homepage so i asked you to design same feature in blog page.

**Comment by Suchitra-Sahoo** [comment]
image
you have added this and in home page the feature looks like this
image

**Comment by MuraliDharan7** [comment]
That is what I have done. The feature looks like that. But in home page someone added this feature. I requested for blog page alone and done the same.

**Pull request merged**
