### PR TITLE
OUR TESTIMONIALS SECTION ADDED

### PR DESCRIPTION
**Pull request by taniya542**
Issue: #1005 
fixes: #1005 

## Description
I have created  Draggable "Our testimonials" section which shows customer reviews. 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
WhatsApp Image 2024-06-30 at 11 43 26_f76c8a96

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by taniya542** [comment]
@Suchitra-Sahoo I have made 5  new blog pages retaining the format and added  lots of pictures.Do let me know if you need any changes.Please review and merge my PR.

**Comment by Suchitra-Sahoo** [comment]
image
You can add some cards like this with arrows to move them for testimonials with name of the person with a picture and few lines. Don't add any blog for each person.

**Comment by taniya542** [comment]
@Suchitra-Sahoo Please review The PR.

**Comment by taniya542** [comment]
@Suchitra-Sahoo Please add the labels too...so that it counts

**Comment by Suchitra-Sahoo** [comment]
Try to nake testimonials section responsive to get level 3 tag.
Currently in smaller devices it looks like this:
image

**Pull request merged**
