### PR TITLE
make more user friendly theme 

### PR DESCRIPTION
**Pull request by visioncoding021**
### Description

- Redesigned the Contact Us and Feedback forms to match the website theme.
- Removed annoying pop-ups and implemented a non-blocking warning and message solution.
- Improved overall user experience by enhancing the visual consistency and functionality.

### Changes

- Updated CSS and HTML for Contact Us and Feedback forms.
- Implemented new JavaScript for non-blocking alerts.

### CODE REVIEW

**Comment by visioncoding021** [comment]
### Description

- Redesigned the Contact Us and Feedback forms to match the website theme.
- Removed annoying pop-ups and implemented a non-blocking warning and message solution.
- Improved overall user experience by enhancing the visual consistency and functionality.

### Changes

- Updated CSS and HTML for Contact Us and Feedback forms.
- Implemented new JavaScript for non-blocking alerts.

**Comment by Suchitra-Sahoo** [comment]
Mention issue number. Add a video or screenshot too.

**Comment by visioncoding021** [comment]
make more user friendly theme #394
make it label also 
Screenshot 2024-05-18 210346
Screenshot 2024-05-18 210709
Screenshot 2024-05-18 210721
alert message disappear after 2 seconds

**Comment by Suchitra-Sahoo** [comment]
Mention your issue number. You provided a PR number.

**Comment by Suchitra-Sahoo** [comment]
Someone is already assigned for contact ssection. You need to raise a PR once the issue is assigned.

**Pull request closed without merging**
