### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by AkshaySobti**
Created an attachment option in the contact us section for GSSoC'24. Updated some spacing between the different options in the Contact Us form.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Mention your issue number. Also add some screenshots of the changes made.

**Comment by AkshaySobti** [comment]
Issue Number: 67
gssoc_agriculture
gssoc_issue

**Comment by AkshaySobti** [comment]
Please review the PR @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts. Also this attachment option is looking odd so improve it.

**Comment by Suchitra-Sahoo** [comment]
You may resolve the conflicts and raise the PR again

**Pull request closed without merging**
