### PR TITLE
Enhance Contact Us Page for Better Visibility and User Experience

### PR DESCRIPTION
**Pull request by Arnavsao**
## Related Issue
The previous Contact Us page lacked visibility and was not user-friendly.

## Description
Replaced the old Contact Us page with a new and improved version. The new page includes inputs for First Name, Last Name, Email, Phone Number, and a Message box, along with Submit and Feedback buttons. The layout has been made responsive, and an image is added to the left side of the contact form.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Before
Screenshot 2024-05-31 at 6 10 52 PM
After
Screenshot 2024-05-31 at 6 05 46 PM

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
None

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Its good. Don't include feedback button in form as now its position is changed. What is that green circular thing towards the right side of form?

**Comment by Suchitra-Sahoo** [comment]
Mention issue number

**Comment by Arnavsao** [comment]
issue number #462
Ohh the green circle is just a Grammarly extension in my laptop.
I have made the required changes you can check it now.
Screenshot 2024-05-31 at 6 50 40 PM

**Comment by Suchitra-Sahoo** [comment]
There is some issue, after merging your PR even after the page is loaded the preloader keeps on working and nothing is visible on screen.
image

**Comment by Suchitra-Sahoo** [comment]
Check whether you have pulled all recent changes

**Pull request merged**
