### PR TITLE
Added "Lets Get Started" in readme.md

### PR DESCRIPTION
**Pull request by AnushkaJainFirst**
@Suchitra-Sahoo ...I have added "Let's Get Started" content below website overview, keeping the rest whole readme.md as it is. Kindly review and merge

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Recently I made some changes in readme to add the contributors so did you pull the changes before making PR?

**Comment by AnushkaJainFirst** [comment]
Yes I forked it again in order to get back the original readme.md content by deleting the previous forked repo
agri-11

**Comment by Suchitra-Sahoo** [comment]
mention issue number

**Comment by AnushkaJainFirst** [comment]
Issue no. : #63

**Pull request merged**
