### PR TITLE
#488 Submit button to disable unless all fields are filled

### PR DESCRIPTION
**Pull request by sanyaP19**
## Related Issue
It becomes compulsory for user to fill all the required fields so as to submit the 'contact us' form

## Description
Submit button will be disabled unless all required fields are filled by the user. The minute all fields are filled, the submit button will be enabled again.

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
The style for button gets changed to show that the button is right now disabled, one has to fill the fields and then the button gets enabled.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Resolve conflicts. Pull all changes from origin. Mention issue number.

**Comment by Suchitra-Sahoo** [comment]
Use some other colour other than gray as it is not looking suitable for website design.

**Comment by Suchitra-Sahoo** [comment]
Have you done the changes? Add a screenshot if its done

**Comment by sanyaP19** [comment]
> Use some other colour other than gray as it is not looking suitable for website design.

Yes it's done

**Screenshot**
image
image

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts

**Comment by Suchitra-Sahoo** [comment]
Kindly pull all changes from origin and resolve the conflicts

**Comment by Suchitra-Sahoo** [comment]
Is it done?

**Comment by sanyaP19** [comment]
> Is it done?

Yes mam!

**Comment by Suchitra-Sahoo** [comment]
you have not pulled all changes to your branch as now the blog page is seperated but it is not reflecting in your branch. So i had to revert your PR.

**Pull request merged**
