### PR TITLE
Mouse follower added and design changed

### LINKED ISSUE #218: A Mouse follower feature
### Describe the feature

I have imagined a good and aesthetic mouse follower that suits the agricultural theme of the website and I would love to add in to enhance the user experience of the website 
Please assign me @Suchitra-Sahoo 

### Add ScreenShots

329868701-f6681079-4cc1-476c-a95f-cfaa903f2b5a
I'll enhance it even more 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Shadyx6**
I have changed the design of mouse follower and made it look even more better for the agricultural theme 

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/140224513/ea2f091a-7752-491a-98e3-558a1a9dd792

My PR fixes #218 issue. @Suchitra-Sahoo Kindly check it and merge it, Thankyou😊

### CODE REVIEW

**Comment by Shadyx6** [comment]
i have resloved conflicts

**Comment by Suchitra-Sahoo** [comment]
@Shadyx6 I had to revert back your PR as the mouse scroller you have made is not moving.

**Comment by Shadyx6** [comment]
Is it working now ??

**Comment by Shadyx6** [comment]
How do I fix it now ? By creating other issue or how please guide @Suchitra-Sahoo

**Pull request merged**
