### PR TITLE
Reverts #640

### PR DESCRIPTION
**Pull request by yeolesanskruti**
## Related Issue
 Issue #628 
## Description
Reverts #640
Added header and footer with proper image background and appropriate changes
## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
LOGIN PAGE -
Screenshot 2024-06-07 160203
Screenshot 2024-06-07 160217
REGISTER PAGE -
Screenshot 2024-06-07 160233
Screenshot 2024-06-07 160256

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

Please kindly review. And assign a level.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
@yeolesanskruti pull all the recent changes and you will see that footer and navbar is present in login page. Footer is fine no need to change that but navbar is not looking same as homepage so just make that change. Your navbar is fine just add it and not need to change footer.

**Comment by yeolesanskruti** [comment]
@Suchitra-Sahoo  I have added the navbar accordingly. I cannot delete the image file, I have deleted the other file not needed accordingly.

Please review. 
@Suchitra-Sahoo kindly mark the level so that my points can be added on the leaderboard.

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts.

**Comment by yeolesanskruti** [comment]
@Suchitra-Sahoo conflicts are resolved.

**Comment by Suchitra-Sahoo** [comment]
After merging your changes i can see just the navbar and no footer.

**Pull request merged**
