### PR TITLE
New Logo

### PR DESCRIPTION
**Pull request by sanskritisahu21**
New named and without named logos

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
add screenshot also

**Comment by sanskritisahu21** [comment]
what do you mean by screenshot?

**Comment by Suchitra-Sahoo** [comment]
Like how the logo is looking on website

**Comment by Suchitra-Sahoo** [comment]
add some image

**Comment by Suchitra-Sahoo** [comment]
use first one and add it to favicon of all pages

**Comment by sanskritisahu21** [comment]
Ok

**Comment by Suchitra-Sahoo** [comment]
is it done?

**Pull request closed without merging**
