### PR TITLE
scrollbar styled in the blog page

### PR DESCRIPTION
**Pull request by Coding-Charvi**
## Related Issue
issue no #560 

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
add screenshot and mention issue number

**Comment by Coding-Charvi** [comment]
@Suchitra-Sahoo Please Check it now i added screenshot and mention issue number.

**Comment by Suchitra-Sahoo** [comment]
@Coding-Charvi the scrollbar should turn green on hover as it is happening in home page. Do the chnages.

**Comment by Suchitra-Sahoo** [comment]
@Coding-Charvi do the changes asap so that you can get your level tag

**Pull request merged**
