### PR TITLE
contact page enhanced

### PR DESCRIPTION
**Pull request by harikasayani**
I have enhanced the contact page.
My issue no #157
Screenshot (78)

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
@harikasayani it is looking a little wierd right now. Try to improve it.

**Comment by harikasayani** [comment]
Hi,
Again I have improved the contact form.
My issue number #157
Screenshot (79)

**Comment by Suchitra-Sahoo** [comment]
This time you have just changed the colour which is not matching with the website. You may explore some other websites and see the styling of the forms and improve.

**Comment by harikasayani** [comment]
Hi,
I have changed the contact form once again and added the icons to become attractive.
Once check it.
Screenshot (80)

**Comment by Suchitra-Sahoo** [comment]
image
Can you add border like this and the symbols which you have shown above. Rest keep the same.

**Comment by harikasayani** [comment]
Hi @Suchitra-Sahoo,
My issue number: #157
Yes I have added border to this contact form now. If there is no conflicts will you merge it.
Screenshot (81)

**Comment by harikasayani** [comment]
Hi @Suchitra-Sahoo 
I have resolved the conflicts please merge it if there is no conflicts.

**Comment by harikasayani** [comment]
Hi @Suchitra-Sahoo 
Wil you merge my pull request.
If there is no conflicts.

**Comment by harikasayani** [comment]
Hi @Suchitra-Sahoo 
I have resolved my conflicts.
Will you merge it.

**Comment by harikasayani** [comment]
Hi @Suchitra-Sahoo,
I have resolved all the conflicts.
Will you please merge it if their is no conflicts.

**Comment by Suchitra-Sahoo** [comment]
Don't change the colour as it is not looking suitable just add the icons and borders. Refer the image I have sent.

**Comment by harikasayani** [comment]
Hi @Suchitra-Sahoo ,
I have recently updated my contact form.
Once please check it.
Screenshot (98)

**Comment by harikasayani** [comment]
Hi @Suchitra-Sahoo 
Please add GSSOC label and level

**Comment by Suchitra-Sahoo** [comment]
I had to revert back your PR because after your changes the feedback option is not visible below contact form. Also the footer section got totally disturbed.
Screenshot 2024-05-18 093911
Screenshot 2024-05-18 093920

**Comment by harikasayani** [comment]
Ok I will do it again

**Pull request merged**
