### PR TITLE
Added More info button

### PR DESCRIPTION
**Pull request by SHANMUGAPRIYA-1**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
More Info button inclusion-Issue #514

## Description
[Please include a brief description of the changes or features added]
There is a division named Blog in the header of this project once the button is clicked various containers appears so i had made changes like More Info button is placed at the bottom of the container so once it is clicked it displays the related brief explanation of the content. But before this there was no button only the user can know the information when the flex is clicked. Now it is more easy for them to know that brief explanation of the container is available.
## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

## Checklist:
- [X ] I have performed a self-review of my code
- [X ] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]
You can know the further information about the content by clicking the More Info button

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
This branch has conflicts. Also this feature is not adding much value to the website because the user was getting redirected to respective blog pages even on clicking the card this option is doing nothing new. Instead it in increasing the size of the card.

**Comment by SHANMUGAPRIYA-1** [comment]
I have made the changes please do check them .

**Comment by Suchitra-Sahoo** [comment]
@SHANMUGAPRIYA-1 can you pls come with some other idea because this more button directs to the blog page and clicking the card also do the same. Instead you can design something like when the user hovers on the card the text part appears which can consist of more feature to read entire blog.

**Comment by SHANMUGAPRIYA-1** [comment]
I had removed that function in the altered code, the functionality is given
only to the More info button.So when the card is clicked it will not be
redirected to the webpages.Functions are given only to the More Info button.

**Pull request closed without merging**
