### PR TITLE
Enhance Navigation Bar

### PR DESCRIPTION
**Pull request by Trevisx07**
## Related Issue
Basically i have enhanced the Navigation Bar.Changes i have done:
1] Added the Hover underline effect as shown in attached video which looks super cool.
2] Had aligned the login button in all section as it was unaligned as i mentioned in the issue.
and add the cart button as it was mentioned in my issue.
Overall i had done these many changes in which the nav bar looks perfect and aligned.
I have attached both Video and Screenshot below.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
1]Video:
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/171925392/be3fab3c-5bb7-42b5-9954-06e285b577d9

2]Screenshot
image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Can you make sure that the navbar looks exactly same in all the pages as it is in home page because in some pages navbar in static, in some some toggle option is not there and in some sliding effect is not there.

**Comment by Suchitra-Sahoo** [comment]
mention issue number also

**Comment by Trevisx07** [comment]
Okay i will

**Comment by Trevisx07** [comment]
Okay.. i will add screenshot of all sections and send.

**Comment by Trevisx07** [comment]
Issue no. #1121

**Pull request closed without merging**
