### PR TITLE
[FEAT]: Enhanced ChatBot

### PR DESCRIPTION
**Pull request by aryansharma220**
Fixes: #329 

From:
https://private-user-images.githubusercontent.com/133234867/331283488-2c5b9250-f22a-4aa7-8618-b1664d09d7c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzgyOTYsIm5iZiI6MTcxNTg3Nzk5NiwicGF0aCI6Ii8xMzMyMzQ4NjcvMzMxMjgzNDg4LTJjNWI5MjUwLWYyMmEtNGFhNy04NjE4LWIxNjY0ZDA5ZDdjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxNjQ2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTgyNWMyZGYwZGVkYThlNjFkMWZkYWIxNmFhYjIzY2VhMzkwOWYxOWZiNDIyOWFjNGQzZjQwMjhlMTE0NjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gq0KMckoZK4joSOpjDCRo03putL6N5DA2Ey35UHjPyE

To:
image

Now the chatbot can give answers without any restrictions and is connected to gemini api so its answers will be more enhanced

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
remove this line I can give information that's most.......     Just write Hi, My name is AgriBoT. I am your Digital Farming Assitant. I am here to guide you through your farming and agricultural needs. Then please type your question. Implement the changes then i'll add the label

**Comment by aryansharma220** [comment]
@Suchitra-Sahoo done

**Comment by Suchitra-Sahoo** [comment]
@aryansharma220 kindly give access to the workflow of the chatbot made by you so that it can be improved further.

**Comment by aryansharma220** [comment]
> @aryansharma220 kindly give access to the workflow of the chatbot made by you so that it can be improved further.

@Suchitra-Sahoo I just found that the website I used to create the chatbot allows only a single person to work on it. I have to upgrade my account to let anyone else work on it, or adding for sharing the workflow. So if you would like, you may provide me the idea and I will implement it. If someone else wants to work on it, you may ask them to ping me I will get it done.

**Pull request merged**
