### PR TITLE
Contact us enhance

### PR DESCRIPTION
**Pull request by tempestanya**
## Description
Enhanced Contact Us Section. I'm creating a new PR from my updated feature branch. 

## Type of PR
- [X] Feature enhancement

## Screenshots / videos (if applicable)
image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

Please check this.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Border is absent add it too

**Comment by tempestanya** [comment]
I didn't plan to add a border in the design, but if you want it then I'll start working on it immediately.

**Comment by tempestanya** [comment]
I have added borders in my code, please check.

**Review by Suchitra-Sahoo — APPROVED** [review]

**Comment by Suchitra-Sahoo** [comment]
issue #829

**Pull request merged**
