### PR TITLE
made changes in navbar section - allignment  resolving issue #301

### PR DESCRIPTION
**Pull request by AdhithiManjunath**
### Summary:
This pull request, my first contribution, addresses alignment issues within the navbar section of our application. It enhances the user experience by ensuring consistency and visual appeal across different screen sizes and devices.

### Changes Made:

- [x] Responsive Alignment
- [x] Flexbox Implementation 

### Screenshots:
**before** 
image

**after** 
Screenshot 2024-05-15 171121

Additional Notes:
- this is my first pull request , so please make sure to highlight if any mistakes are present

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
I have checked the website and I can find the elements of navbar are aligned properly. You are facing this kind of issue in which device?

**Comment by AdhithiManjunath** [comment]
i am able to see the mismatch in allignment in desktop screen , you too can have a look https://suchitra-sahoo.github.io/AgriLearnNetwork/

**Comment by Suchitra-Sahoo** [comment]
Keep the icon one left side only and remove the space after contact

**Comment by Suchitra-Sahoo** [comment]
when i merged your PR the allignment totally got disturbed. So had to revert back your PR
Screenshot 2024-05-16 211052

**Comment by AdhithiManjunath** [comment]
sorry for this inconvenience , ill look into it and check where it went wrong  !!

**Pull request merged**
