### PR TITLE
Change in style of home page

### PR DESCRIPTION
**Pull request by Shreyaa173**
Change in styling of issue #525

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Kindly add a screenshot soon to merge your PR

**Comment by Shreyaa173** [comment]
image
before
Screenshot 2024-05-29 145743
the changes

**Comment by Suchitra-Sahoo** [comment]
Pull all the recent changes from origin

**Comment by Suchitra-Sahoo** [comment]
Have you done?

**Comment by Shreyaa173** [comment]
> Have you done?

done

**Comment by Suchitra-Sahoo** [comment]
I had to revert back your PR as the carousel is not moving properly also the text is not visible clearly in the last image

**Pull request merged**
