### PR TITLE
#840 Issue resolved

### PR DESCRIPTION
**Pull request by AryanAwtar**
## Related Issue
#840 
## Description
- Improved the delay time of scroll
- improved the `welcome content` div
- also applied text formatting in the entire index.html

## Type of PR

- [X] Bug fix
- [X] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

Screenshot 2024-06-13 161654
`Learn` `Sow` `Grow` all in one line not like previous

# Have A Look To This Video  
## it shows the scroll button function without any lag or delay
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/67885970/694df318-a4a6-45ca-b05e-f0af4bb1db4c

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts

**Comment by AryanAwtar** [comment]
removed the conflict

**Comment by Suchitra-Sahoo** [comment]
image
recently homepage is updated which is not visible in your branch so pull all changes.

**Comment by Suchitra-Sahoo** [comment]
Screenshot 2024-06-19 140114
scroll to top option is looking like this.

**Pull request merged**
