### PR TITLE
Feat:Want to Add Backend OF Contact Page Where User will also get Acknowledgment mail on Submitting #1148

### PR DESCRIPTION
**Pull request by nishant0708**
## Related Issue
Wrote Backend Of Contact Us page and User is receiving Acknowledgment Mail

## Description
to make it work 
Create One .env File with these details
DB_URI="Mongo db Url"
EMAIL_USER=your_email@example.com
EMAIL_PASS=your_email_password

to create Email PAss  check this video https://www.youtube.com/watch?v=hXiPshHn9Pw&t=27s

to run backend do

cd backend 
npm start /node server.js

## Type of PR

- [ ] Bug fix
- [X ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot 2024-07-28 170357
Screenshot 2024-07-28 170422

## Checklist:
- [X ] I have performed a self-review of my code
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @Suchitra-Sahoo please review this as soon as possible as you know the competion is coming to end .Thanks. And let me know changes if any

**Comment by Suchitra-Sahoo** [comment]
issue #1148

**Comment by nishant0708** [comment]
Hey @Suchitra-Sahoo you have removed both the levels atleast assign one level label

**Comment by Suchitra-Sahoo** [comment]
> Hey @Suchitra-Sahoo you have removed both the levels atleast assign one level label

Labels are already there

**Pull request merged**
