### PR TITLE
fixed css of footer in signup page

### LINKED ISSUE #1228: Feat: footer of sign in page
### Describe the feature

footer is not same as other page

### Add ScreenShots
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhairyagothi**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
closes #1228 
## Description
[Please include a brief description of the changes or features added]
fixed
image

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@Suchitra-Sahoo please merge PR

**Comment by Suchitra-Sahoo** [comment]
Your screenshot is not visible

**Comment by dhairyagothi** [comment]
@Suchitra-Sahoo  check now done

**Comment by dhairyagothi** [comment]
Screenshot 2024-07-23 104735

check now @Suchitra-Sahoo

**Pull request merged**
