### PR TITLE
home page improved

### PR DESCRIPTION
**Pull request by harinisayani**
I have changed the font-color, background-color and image radius to appear the home page clear and beautiful.

### CODE REVIEW

**Comment by harinisayani** [comment]
My issue number #160
Screenshot (76)

**Comment by Suchitra-Sahoo** [comment]
@harinisayani I feel the previous one was much better. Try to improve as the changes you have made is not suitable.

**Comment by harinisayani** [comment]
ok. I will try it.

**Comment by harinisayani** [comment]
I have improved this.
my issue no: #160
Screenshot (77)

**Comment by harinisayani** [comment]
Hi,
Actually there is no conflicts in my code. But when I see it now there is another code merged into it.
Could you please tell me how to resolve it.

**Pull request closed without merging**
