### PR TITLE
Fixed navbar alignment and made responsive

### LINKED ISSUE #694: Tabs of navbar in blog page are not at proper place
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The tabs of the navbar in the blog page are not at proper place which make the page look bad. I will put them at right place.

image

Please assign this to me under gssoc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Shreesanyog**
Fixes #694 

## Description
Tabs of the navbar in blog page are not aligned properly and are not responsive. I have solved the issue and  fixed the tabs at proper place and made responsive.

## Type of PR

- Bug fix

## Before

image

-----
## Video

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/166977453/6cb2531f-5bac-4c4e-b76e-cb914450a968

-----

image

-----
image

image

image

## Checklist:
- I have performed a self-review of my code
- I have read and followed the Contribution Guidelines.
- I have tested the changes thoroughly before submitting this pull request.
- I have provided relevant issue numbers, screenshots after making the changes.
- I have commented my code, particularly in hard-to-understand areas.

-----
<h3>Kindly  merge it and please give the label of gssoc and level for both issue and PR.</h3>

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Kindly check the position of search bar to be in centre when screen size is reduced. Login option is going below the navbar correct that too. After doing all these changes attach a video.

**Comment by Shreesanyog** [comment]
@Suchitra-Sahoo I have placed the search bar at center when screen size is reduced. I have fixed the login button issue , now it is inside the navbar. And I have also attached a video to showcase these changes.

**Comment by Shreesanyog** [comment]
@Suchitra-Sahoo I have placed the search bar at center when screen size is reduced. I have fixed the login button issue , now it is inside the navbar. And I have also attached a video to showcase these changes.


https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/166977453/4ca56f27-297f-4b74-aba0-14fa53697a5b

**Comment by Suchitra-Sahoo** [comment]
on my side search bar is like this
image
I think you have not pulled changes

**Comment by Shreesanyog** [comment]
I have made another PR by updating the fork and fixed the search bar  design as well kindly refer the below link for the PR.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/pull/725

**Pull request closed without merging**
