### PR TITLE
fix: the login/register button in wrong place

### LINKED ISSUE #686: BUG: Button in the navbar should in the right place
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The button is not is not in its current place 
image
we can ad

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by upsaurav12**
## Related Issue
fixes #686 

## Description
In this the ``login`` button was not in correct place it looking like this 
image

**After Fix **
it is looking like this 
image

 
## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by upsaurav12** [comment]
Hi @Suchitra-Sahoo i have raised PR pls look into it

**Comment by Suchitra-Sahoo** [comment]
For large screen the position of login is correct, the problem is in small devices the login option is going out
image

**Comment by Suchitra-Sahoo** [comment]
image

**Comment by upsaurav12** [comment]
So i think i should reduce gap between them as there is some gap above the ``home`` link

**Pull request merged**
