### PR TITLE
look of faq page

### PR DESCRIPTION
**Pull request by Hemav009**
## Related Issue

#848 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109607812/e77cad26-a450-4f00-86aa-1cfdbaf3f0d5

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
I think FAQ page was looking much better earlier as compared to this one.

**Comment by Hemav009** [comment]
image


Screenshot 2024-06-22 182432


Do you like either of these looks?

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts as recently some changes are made in faq page

**Comment by Hemav009** [comment]
Uploading faqqq.mp4…

**Comment by Suchitra-Sahoo** [comment]
Recently a feature was added in faq in which one question closes on opening the other which is missing here. Also the card is almost touching the scrollbar so bring it to a correct position.

**Pull request merged**
