### PR TITLE
Poppins font added

### PR DESCRIPTION
**Pull request by chaanakyaaM**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
Closes issue: #1018 

## Description
[Please include a brief description of the changes or features added]

I have changed the website's default font to poppins

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
add some screenshot of changes made

**Comment by chaanakyaaM** [comment]
screen shots:

Screenshot (306)
Screenshot (307)
Screenshot (308)
Screenshot (309)

**Comment by Suchitra-Sahoo** [comment]
image
There should be some spacing between AgriLearnNetwork and home option. Apply font in blog and about page also.

**Comment by chaanakyaaM** [comment]
shall i create a new PR for spacing between AgriLearn Network?

**Comment by chaanakyaaM** [comment]
And would you kindly add level1 and gssoc labels to this PR.

**Comment by Suchitra-Sahoo** [comment]
> And would you kindly add level1 and gssoc labels to this PR.

it will be added in the final PR

**Comment by chaanakyaaM** [comment]
ok

**Pull request merged**
