### PR TITLE
signup and login page

### PR DESCRIPTION
**Pull request by MattipaPoojitha**
issue num: #11 @Suchitra-Sahoo   created Login and registration  page:

1. REGISTRATION PAGE:
gssoc1

2. LOGIN PAGE
gssoc2-min

 3. HOME PAGE 
 
gssoc3-min

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
@MattipaPoojitha can you just design signup and login page using html, css and javascript and link it to backened.

**Comment by MattipaPoojitha** [comment]
I have done the same but I need to add that login one on main screen right so that users can click that to login ...I have done the same I modified a bit of extisting html and since I used PHP for backend I made main file also as php to support and it is showing conflicts there

**Comment by MattipaPoojitha** [comment]
If you don't want me to add that login page in main screen then I can share only my login and sign up with backend

**Comment by Suchitra-Sahoo** [comment]
yes do that. pull all changes from origin and raise another pr

**Comment by MattipaPoojitha** [comment]
Okk I will send by tomorrow evening check that once

**Pull request closed without merging**
