### PR TITLE
newsletter is added in footer

### PR DESCRIPTION
**Pull request by Srujitha-Raghava**
## Related Issue
#482 

## Description
[Please include a brief description of the changes or features added]
A subscribe button with newsletter feature is added in the footer

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot 2024-05-29 104700

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Srujitha-Raghava** [comment]
@Suchitra-Sahoo please review the changes mam

**Comment by Suchitra-Sahoo** [comment]
@Srujitha-Raghava again pull all the changes from origin as after merging your PR some changes were not visible so i had to revert it. Do it as soon as possible by raising another PR

**Comment by Srujitha-Raghava** [comment]
Screenshot 2024-05-30 100136

@Suchitra-Sahoo everything is up-to date

**Comment by Suchitra-Sahoo** [comment]
Okay check is the  feedback form opening on clicking the feedback button? Because when i merged your PR it stopped working and when i reverted it , it got normal.

**Pull request merged**
