### PR TITLE
User can now exit from the chatbot using the exit option.

### PR DESCRIPTION
**Pull request by DevanshuSinghai**
the exit option and the name of the bot is now visible which were previously hidden by navbar, now user can exit chatbot using the exit option and the name of the bot is also visible.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
@DevanshuSinghai add some screenshots about the changes made.

**Comment by Suchitra-Sahoo** [comment]
Mention your issie number too.

**Comment by DevanshuSinghai** [comment]
my issue number is #46 
these are the screenshots 

before 
Screenshot 2024-05-10 204822

after
Screenshot 2024-05-10 204850

**Comment by Suchitra-Sahoo** [comment]
You need to wait for the issue to be assigned and then start working and raise PR. Also someone is already been assigned this issue.

**Pull request closed without merging**
