### PR TITLE
Resolved #321,Carousel Component is added instead of a slideshow in home page

### LINKED ISSUE #321: BUG: Slide Show in home page is not working properly and it is sliding too fast.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Slides are automatically sliding at faster rate and after reaching the third slide it is coming back to the first slide and start sliding. Instead of that, I can make them to slide in loop using Bootstrap.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by VarshaKammari**
Carousel Component is added.  After adding the bootstrap cdn link, there is some change in the font-weights of different headongs. So, I changed the font-size and font-weights in order to have the previous view of the webpage.

Here is the video demonstrating the changes, I made in the website.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114400934/821f65c7-1405-4b9e-9645-1b8014d4c116

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Pull all the changes from origin as recently the blog section has been updated. Mention your issue number.

**Comment by VarshaKammari** [comment]
Okay

**Comment by VarshaKammari** [comment]
I pulled all changes from origin and the updated features doesn't effect the functionality that I added. My issue number is #321

Here is the video demonstrating the changes, I made. 

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114400934/edb183fd-cb73-4812-8d08-eec94bb6d7e3

**Comment by Suchitra-Sahoo** [comment]
Why there is so much time gap between first and second image? And i can see 3 images what about the rest?

**Comment by VarshaKammari** [comment]
The time gap between first slide and second slide is because of network issue.All the four slides are sliding one after the other with the same time gap.After reaching the last slide it is  automatically directing it to the first slide without moving in Anti-clockwise direction.

**Comment by Suchitra-Sahoo** [comment]
I had to revert back your PR because after merging your changes I found that images are not moving apart from the first 2 and that also with a lot of time gap.

**Comment by VarshaKammari** [comment]
I will check and fix the issue.

**Comment by VarshaKammari** [comment]
I just now rechecked my code. And executed in two of my browsers. It is executing perfectly. But, it is taking some time to load the first slide to move to the next slide because of bootstrap cdn link.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114400934/09874e5b-8f2e-4616-a09f-1546e9f622db

**Pull request merged**
