### PR TITLE
Fixed the toggle button

### PR DESCRIPTION
**Pull request by Bhumika1312**
## Related Issue
Fixes: #859 

## Description
Made the necessary changes to the toggle button to ensure proper alignment on small screens.

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Large Screen:

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/115869626/27966944-7ae0-4bd6-905e-01add04838fc

Small Screen:

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/115869626/9ce8440a-8aba-4151-b8ea-74f4a2c48673

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Add a video to demonstrate your changes. Both for large as well as small screens.

**Comment by Bhumika1312** [comment]
Large Screen: 


https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/115869626/f4d4eb2d-363e-47b4-92d5-dc2d77ceece0


Small Screen:

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/115869626/0d277642-3a4d-4150-a347-ae4111607bd9

**Comment by Bhumika1312** [comment]
@Suchitra-Sahoo Please assign it to me and add label and level
Thank you

**Comment by Suchitra-Sahoo** [comment]
image
Screenshot 2024-06-16 135433
When i am clicking on toggle option it is not changing to dark mode. The mode option is almost at the edge of navbar which is not looking good. In small screen the mode option is overlapping close option of menu. I think you have not pulled changes from origin as now the navbar issue is resolved and login option is within navbar. To get better idea about toggle otpion just reer gssoc official website.

**Comment by Suchitra-Sahoo** [comment]
What is your issue number?

**Comment by Suchitra-Sahoo** [comment]
849 is PR number

**Comment by Bhumika1312** [comment]
#823

**Comment by Bhumika1312** [comment]
@Suchitra-Sahoo After making those changes do I have to open a new PR or update in this one only

**Comment by Suchitra-Sahoo** [comment]
823 isuue is already assigned to you.

**Comment by Suchitra-Sahoo** [comment]
Keep the toggle mode on navbar only but not totally at the edge it should have proper space.

**Comment by Suchitra-Sahoo** [comment]
image

**Comment by Suchitra-Sahoo** [comment]
image

**Comment by Suchitra-Sahoo** [comment]
Make a new PR

**Pull request merged**
