### PR TITLE
Update footer copyright year to be dynamic

### PR DESCRIPTION
**Pull request by SaiTejaswaniBikkasani**
Fixed issue #179 

This pull request updates the footer copyright year to be dynamically generated using JavaScript. The current year is now displayed automatically, ensuring that the year is always up-to-date without manual intervention. This improves the user experience by reflecting the current year in the copyright notice.

### CODE REVIEW

**Comment by SaiTejaswaniBikkasani** [comment]
Hey @Suchitra-Sahoo, Is everything ok with my pull request. Please, kindly tell me if any changes are needed regarding to the pull request you merged. 

You merged my pull request but you did not assign the gssoc labels**. Please assign the gssoc labels.**

**Comment by Suchitra-Sahoo** [comment]
I had to revert back your PR as you might have not pull all changes from origin to your branch before raising the PR because of which recent changes are not visible.

**Comment by SaiTejaswaniBikkasani** [comment]
Am I allowed to make the changes again and pull a request. If it is ok, then I will again do a pull request.

**Comment by Suchitra-Sahoo** [comment]
Yes you can make another PR by pulling all the changes and mention your issue number.

**Pull request merged**
