### PR TITLE
Styled feedback button

### LINKED ISSUE #553: IMPROVE FEEDBACK BUTTON STYLING
### Describe the feature

Change CSS properties to style the feedback button 

### Add ScreenShots

Updated:
new updated

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ayushkrrana**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description
Change CSS properties to style the feedback button

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
new updated

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

closes #553  @Suchitra-Sahoo

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Even after merging your PR I Can't see any change
image

**Comment by Suchitra-Sahoo** [comment]
@ayushkrrana Kindly check why the feedback form is not opening on clicking it

**Comment by ayushkrrana** [comment]
> @ayushkrrana Kindly check why the feedback form is not opening on clicking it



> @ayushkrrana Kindly check why the feedback form is not opening on clicking it

i have checked it in my local repo , it work on that i don't know why it did not work in the main repo i will share you the video 

Uploading vid.mp4…


Uploading vid.mp4…


Uploading vid.mp4…


Uploading vid.mp4…

**Comment by Suchitra-Sahoo** [comment]
Okay try to pull changes from origin and then see.

**Comment by ayushkrrana** [comment]
> The issue is resolved



> The issue is resolved

Ok, There is no photo shown of me in the contribution part 
@Suchitra-Sahoo

**Pull request merged**
