### PR TITLE
Added seperate blog page

### PR DESCRIPTION
**Pull request by Hemav009**
## Related Issue
#463

## Description
I created a separate blog page and added two other blogs to the page, check below ss.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot 2024-05-23 193401
on clicking ..moreblogs user can go to blog page
Screenshot 2024-05-23 193413
below are blogs on Smart Farming and AI in farming.(created using HTML and CSS).
Screenshot 2024-05-23 193424

Screenshot 2024-05-23 193432

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

@Suchitra-Sahoo 
Please merge it.
Thank YOU!

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
@Hemav009 currently i don't want you to add new blogs. Write blogs for already existing topics in blog section. Also you have created seperate pages which opens when the user goes to blogs section and click on any particular card. But i wanted you to make a separate blog page which gets activated when user clicks on blog option of navbar. Then the user should click on the desired topic card which opens the page in which you will write your own blog.

**Comment by Suchitra-Sahoo** [comment]
YES all the 12

**Comment by Hemav009** [comment]
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109607812/9423a0a2-f55c-4e98-ad3a-81276453d14d



is this ok?

**Comment by Suchitra-Sahoo** [comment]
Raise another PR with fresh changes.

**Pull request merged**
