### PR TITLE
Added Product Page

### PR DESCRIPTION
**Pull request by Ishaparte**
## Related Issue
#564 Created a Buy Product Page for Farmers

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/113294672/3a5315d1-2493-4504-a795-2e2a3ad0244b

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Please don't add this on home page create a separate page.

**Comment by Suchitra-Sahoo** [comment]
And don't make any changes in home page

**Comment by Ishaparte** [comment]
I have created a separate page

**Comment by Suchitra-Sahoo** [comment]
Create a services option in navbar under which create a option Buy products and attach your page there. Also remove all the changes made on home page. I can see the social icons in footer can't be seen but on my side its perfectly fine so look into it.

**Comment by Suchitra-Sahoo** [comment]
If you have made the changes kindly attach a video.

**Comment by Ishaparte** [comment]
I have already attached the video

**Comment by Suchitra-Sahoo** [comment]
There are conflicts in this branch

**Comment by Ishaparte** [comment]
Done

**Comment by Suchitra-Sahoo** [comment]
No change is visible as it is showing the files are deleted. Create another PR with all the files again.

**Pull request merged**
