### PR TITLE
Agri bot is updated and is fully functioning

### PR DESCRIPTION
**Pull request by nagamukesh**
I have deployed a chatbot of my own and updated the existing one as an agribot, which is functioning. It answers all the questions related to the AgriLearn Network website and agriculture.
@Suchitra-Sahoo Thanks for giving me this opportunity.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
add a video to see how the chat bot is working after the changes.

**Comment by nagamukesh** [comment]
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/112798996/33166325-2c48-4a7c-be3e-710b9ae1e657

I have made chat bot fully functional as one can see in the video
I made sure ai chatbot can make use of google web search for other agriculture-related questions

**Comment by Suchitra-Sahoo** [comment]
Don't change the design and colour of the bot. Also the closing option of the chatbot is hidden by the navbar. Just work on the functioning part of the chatbot.

**Comment by nagamukesh** [comment]
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/112798996/80868da4-d140-4e9a-b3c0-aa3f14fd02a8

I havent changed the layout of the chat bot, as you can see, it is in the right corner as usual. I have just changed the functioning of the bot

**Comment by Suchitra-Sahoo** [comment]
I guess you have not pulled the changes from origin. Do it and also resolve the conflicts.

**Comment by Suchitra-Sahoo** [comment]
I'm closing this PR, you make the changes and raise another PR.

**Pull request closed without merging**
