### PR TITLE
Contact form updated both the issues resolved #518 and #519

### LINKED ISSUE #518: Home Page Improvement and Contact Us Form UI Updation
### Describe the feature

Hey @Suchitra-Sahoo I visited this website and noticed few issues that I can resolve. I attached relevant screenshots for reference.
The website sections that I can contribute to update are: 

1. In home page the first section's text "Welcome to AgriLearnNetwork"  is not clearly visible or little bit blurry due to the background images. I want to update this and make it more clear and easily readable.

2. The Contact Us section's UI needs improvement, the feedback section is not clearly visible and I also want to update the UI of Contact Us section to make it more interactive and if possible allow me to change the color from all green.

### Add ScreenShots

Screenshot for 1st issue: 

Screenshot 2024-05-27 194923

Screenshot of 2nd issue: 

Screenshot 2024-05-27 195242

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by GauriGupta21**
Contact form updated 
I have updated the contact us form as @Suchitra-Sahoo  you mention in the comment. Kindly check it and approve it  
I do a humble request to assign me label.
image

## Type of PR

- [ X] Feature enhancement

## Checklist:
- [X ] I have performed a self-review of my code
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
but is still showing conflicts

**Comment by GauriGupta21** [comment]
@Suchitra-Sahoo I resolved all conflicts and please check all the changes. Also please add relevant GSSoC level label.

**Comment by Suchitra-Sahoo** [comment]
Its not working. After merging your PR due to some reason the preloader keeps working even after the page is loaded
image

**Comment by Suchitra-Sahoo** [comment]
If you want to create this kind of contact form then create a separate page or if you want to add in main page then keep its size small.

**Comment by Suchitra-Sahoo** [comment]
If you are creating a seperate page don't keep the background dark green

**Pull request merged**
