### PR TITLE
navbar transition

### PR DESCRIPTION
**Pull request by anjalidsingh**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description
navbar transitions to a transparent background upon scrolling down and enhanced testimonials by changing color of it.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by anjalidsingh** [comment]
Uploading Untitled video - Made with Clipchamp (1) (1).mp4…

video

**Comment by Suchitra-Sahoo** [comment]
your video is not uploaded. Mention your issue number

**Comment by Suchitra-Sahoo** [comment]
i can't see any changes in navbar. Keep card colour same only.

**Comment by anjalidsingh** [comment]
As soon as I scroll down in video(I attached) the transparent green navbar vanishes whereas logo and icons remains same for better visibility. This is what I meant by navbar transition. Should I change card color back to mint green if you approve navbar transition?

**Comment by Suchitra-Sahoo** [comment]
This feature is not suitable as options are not visible clearly.

**Pull request closed without merging**
