### PR TITLE
Enhanced the Nav bar by aligning the login button and adding hover underline effect.

### PR DESCRIPTION
**Pull request by Trevisx07**
## Related Issue
Basically i have enhanced the Navigation Bar.Changes i have done:
1] Added the Hover underline effect as shown in attached video which looks super cool.
2] Had aligned the login button in all section as it was unaligned as i mentioned in the issue.
and add the cart button as it was mentioned in my issue.
Overall i had done these many changes in which the nav bar looks perfect and aligned.
I have attached both Video and Screenshot below.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Prevoyance_Draft

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Trevisx07** [comment]
Issue no. #1125

**Comment by Trevisx07** [comment]
I had attached all scrnsht of all navbars as per your suggestion.

**Comment by Trevisx07** [comment]
@Suchitra-Sahoo The current navigation bar of website was unaligned especially the login button and it was different for all sections . i have fixed the alignment of that and additionally i had added the underline hover efffect in the nav bar which looks pretty amazing.

**Comment by Suchitra-Sahoo** [comment]
image
In blogs page when we scroll fown then the login option is going behing toggle option. Please fix it and i'll assign you level2 tag

**Comment by Trevisx07** [comment]
Done @Suchitra-Sahoo ! Can check the new PR.
Thank you:)

**Pull request merged**
