### PR TITLE
Commit

### PR DESCRIPTION
**Pull request by Damini2004**
## Related Issue
#801 
#801 
## Description
Language translator has been implemeted successfully. Kindly review it.
## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/119414762/1dcd275c-f009-48f4-a1b4-192debf9ad63

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Kinldy review it and add relevent level to the PR.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Everything in navbar has got mixed up. The language changing option should look similar to other navbar options. Keep only indian languages.

**Comment by Damini2004** [comment]
@Suchitra-Sahoo  Yes for that we have alter some changes in css file for alignment.
For similarity it will be achieved in  next commit.
As it is Provided by google so all language are inlcuded so in order to customize the language as per your point of view then it will more lengthy.

**Comment by Suchitra-Sahoo** [comment]
Okay but then this feature will not be useful for the website. I am attaching an example where you can see that there are only few specific languages and the option is matching with navbar too.
image

**Comment by Suchitra-Sahoo** [comment]
So inform me whether you will be able to create something like this or not.

**Comment by Damini2004** [comment]
@Suchitra-Sahoo  Yes i can customize the types of language, that it will consist of indian native languages.
I can style the navbar in proper manner.
@Suchitra-Sahoo

**Comment by Damini2004** [comment]
image

gothrough it

**Comment by Suchitra-Sahoo** [comment]
Try to make something as provided by me in previous image bcs the second one is very simple and will look totally different in navbar.

**Comment by Damini2004** [comment]
@Suchitra-Sahoo  Its just the image depicts that i can integrate the native indian languages i will add more styling to it. 
Kinldy open the issue i want to work on it.

**Pull request closed without merging**
