### PR TITLE
#added no search found message and [placed the footer at a proper distance from the search bar when no search found

### PR DESCRIPTION
**Pull request by nandani-goyal**
## Related Issue
#1057 
solves issue raised in pull request #1091 

## Description
I have added the search bar to the buy products page and also the heading Agroproducts. Now when no search is present the screen will display the message "no search result found" and the footer also is hidden now.

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/152094228/4777c973-4ff4-4aee-8a00-504c61093f04

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
No need to remove the footer it should be present. You can see blog section there also search bar is working and the footer is also working fine.

**Comment by nandani-goyal** [comment]
No the footer is not hidden. It is kept at a distance from the search bar when there is no search found.You can have look the footer is placed at a distance same as that in blogpage.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/152094228/8c5be853-1bd8-48c7-808e-e9ea81c67d2b

**Comment by Suchitra-Sahoo** [comment]
image
The search bar is somewhere behind the navbar.

**Comment by Suchitra-Sahoo** [comment]
fix it

**Pull request merged**
