### PR TITLE
changed to the correct year in the blogpage

### PR DESCRIPTION
**Pull request by shivathmikavemula**
Hello PA 
I have made a change in the blogpage.html and changed to the correct year in it.

### Screenshot -

Screenshot (15)

### CODE REVIEW

**Comment by shivathmikavemula** [comment]
I have made a correction in the blogpage.html and corrected the year. I request to allot the gssoc levels @Suchitra-Sahoo 
and merge it.

**Comment by shivathmikavemula** [comment]
I request you to allot the labels @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
What is your issue number?

**Comment by shivathmikavemula** [comment]
BUG: in the blogs page the time is not correct #619

**Comment by shivathmikavemula** [comment]
please provide the gssoc level/ labels to it. My issue no. is #619

**Comment by shivathmikavemula** [comment]
### Issue number #619 @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
@shivathmikavemula kindly don't raise a PR before the issue is assigned to you. I can't assign you the issue because one of the contributor is already working on it.

**Pull request closed without merging**
