### PR TITLE
update cart ui and make seperate route and make it functional

### LINKED ISSUE #1162: Feat: Redesing cart
### Describe the feature

@Suchitra-Sahoo 

i would like to work on redesign cart ui

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

@Suchitra-Sahoo 

Feat: Redesing cart #1162

close #1162

## Description
[Please include a brief description of the changes or features added]

- added cart ui and make it fully functionals

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

https://github.com/user-attachments/assets/8ddb5951-2f48-40e3-ad2b-29c49f6fd229

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

kindly check this and merge it

**Comment by Suchitra-Sahoo** [comment]
Don't create a seperate route. Just improve the design of the cart. Currently it is very basic , also improve the checkout button.

**Comment by dhruv8433** [comment]
oky

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

kindly please review it and merge it
if you need any modifications, please inform me

**Comment by Suchitra-Sahoo** [comment]
pls improve the addition and deletion button too in cart. Resolve the conflicts and pull all changes from origin.

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

i update plus and minus button and add hover effect now you can merge it

image

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo

i update plus and minus button and add hover effect now you can merge it

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo

i update plus and minus button and add hover effect now you can merge it

**Comment by Suchitra-Sahoo** [comment]
When there is no item in cart it is looking like this
image
Also the checkout button should not work when there is no item in cart

**Comment by dhruv8433** [comment]
Ok @Suchitra-Sahoo 

I will create new issue for that

**Pull request merged**
