### PR TITLE
fixed the footer issue no - #17 and #18 ( combined PR)

### PR DESCRIPTION
**Pull request by kairveeehh**
1. centring the copyright segment
2. making the footer more better and adding icons 
3. on hover for mail visibility
Screenshot 2024-05-10 004917
Screenshot 2024-05-10 010648

### CODE REVIEW

**Comment by kairveeehh** [comment]
@Suchitra-Sahoo  please count it as a merged for both the issues that were assigned to me 
thankyi=ou and working on the rest :)

**Comment by kairveeehh** [comment]
@Suchitra-Sahoo  it shows conflicts , please can you elaborate what has to be done?

**Comment by Suchitra-Sahoo** [comment]
Try to pull changes from origin and then try.

**Comment by kairveeehh** [comment]
> Try to pull changes from origin and then try.

@Suchitra-Sahoo but actually it comes because of the alignment and icon issues in the file as a previous PR  was merged so to keep it like the images I have attached that has to be overwritten

**Comment by kairveeehh** [comment]
@Suchitra-Sahoo I would like to reconfirm that due to the issue #13 merged few minutes ago , the alignment has been disrupted and that is creating conflicts just recently , as my PR was raise much before with no issues , so I would request you to overwrite it or suggest the needful .
thankyou

**Comment by Suchitra-Sahoo** [comment]
I can't merge your PR. You need to resolve the conflicts.

**Pull request closed without merging**
