### PR TITLE
seperate bloog pagee

### PR DESCRIPTION
**Pull request by Hemav009**
## Related Issue
#463 

## Description
please merge it one last time. i have resolved issues.
refer video below.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109607812/77f151e8-aff7-4b2c-b1c1-5f51be792cb5

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Make corrections in margin of the cards. Also there is no way to go back to the home page.

**Comment by Hemav009** [comment]
Okay I will add a option to go back in navbar and Increase the margin

**Comment by Suchitra-Sahoo** [comment]
@Hemav009 in back to home option make the text size same as navbar options and add a symbol like arrow or something.

**Comment by Hemav009** [comment]
@Suchitra-Sahoo  do I have to make another pr for changes?

**Pull request merged**
