### PR TITLE
Added_Expert_section

### PR DESCRIPTION
**Pull request by tishubohra**
## Related Issue
There was no expert section ,we can create expert section.

## Description
We have experts for different type of plants, who can help you clearing your doubts regarding growing of plants. There is a courser for scrollling horizontally to see different experts.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

image
image

### CODE REVIEW

**Comment by tishubohra** [comment]
The home page looks like this after adding this section-
image

**Comment by Suchitra-Sahoo** [comment]
mention issue number

**Comment by tishubohra** [comment]
> mention issue number

It's #705

**Comment by Suchitra-Sahoo** [comment]
Please don't raise a PR before the issue is assigned to you. Also this feature is not required right now.

**Pull request closed without merging**
