### PR TITLE
Improvied Home and Blogs page

### PR DESCRIPTION
**Pull request by gopalepic**
1) Improved text quality on the home page results to better attractive home page 

2) Changed the height of the blogs , Now blogs need less space and working great, 

Both the changes are done after keep in mind about the code_of_Coduct .

I hope my contributions made you website to an next level in apperence

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Mention your issue number. Add a video or screenshot too.

**Comment by gopalepic** [comment]
@Suchitra-Sahoo  actully i marked that issue as done by mistake , I am new to opensource , it was mistake of mine ,

btw , I mentioned both the issues above via text , tell me explain them again

 1)  In the first screen shot , I adjusted the blurry text , initially it looks like an blurry image and was descresing the reputation of this excellent website 

 2)   I adjusted the blogs height , initially all blogs were taking a bit extra space , now I adjusted that 
Screenshot 2024-05-18 183957
Screenshot 2024-05-18 184049

**Comment by gopalepic** [comment]
@Suchitra-Sahoo  pls have a look the PR

**Comment by Suchitra-Sahoo** [comment]
Dates are not aligned properly.

**Comment by gopalepic** [comment]
@Suchitra-Sahoo   my task was not related to dates , it was related to the blogs height , I make them a bit concise and better looking

**Pull request closed without merging**
