### PR TITLE
Added Hamburger in BuyProducts Page

### LINKED ISSUE #1250: DOC: adding Hamburger in product page navbar
### What's wrong with the existing documentation

there is no hamburger

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhairyagothi**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
closes #1250 
## Description
[Please include a brief description of the changes or features added]
Added
image

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@Suchitra-Sahoo please merge PR

**Comment by Suchitra-Sahoo** [comment]
resolve conflicts so is it responsive for all screen sizes?

**Comment by dhairyagothi** [comment]
@Suchitra-Sahoo resolved 
yes navbar is responsible but page is not responsible i will make it responsible by raising another issue

**Comment by Suchitra-Sahoo** [comment]
image
Login option is lowing out.

**Comment by dhairyagothi** [comment]
> image Login option is flowing out.

that problem is with navbar of every page i will resolve it creating an issue for that

**Pull request merged**
