### PR TITLE
Add about us page

### LINKED ISSUE #891: Feat: Improve about us section
### Describe the feature

The current 'About Us' section lacks the best user experience. Therefore, I would like to create a separate page for 'About Us.'

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by DharshiBalasubramaniyam**
## Related Issue
fixes #891 

## Description

1. I have created separate page for about us.
2. About us page is responsive.
4. updated about us link in each html files.
5. removed about us section from index.html.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

Screenshot 2024-06-26 210230

Screenshot 2024-06-26 210305

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

Kindly please let me know if any changes required!

### CODE REVIEW

**Review by Suchitra-Sahoo — APPROVED** [review]

**Comment by DharshiBalasubramaniyam** [comment]
@Suchitra-Sahoo can you please provide level 2 badge for this pr. I have added a new separate page. I think the changes might be enough the get a level 2 badge.

**Comment by Suchitra-Sahoo** [comment]
Okay but before that change the font of about page to the one as in home page.

**Comment by Suchitra-Sahoo** [comment]
Before doing that pull all the changes from origin

**Comment by DharshiBalasubramaniyam** [comment]
> Okay but before that change the font of about page to the one as in home page.

Sure. May I create a new pr?

**Comment by Suchitra-Sahoo** [comment]
Yes you can but i'll add the level in this PR so mention your PR number and issue number in your new PR.

**Comment by DharshiBalasubramaniyam** [comment]
> Yes you can but i'll add the level in this PR so mention your previous PR number and issue number in your new PR.

Sure. Got it.

**Comment by DharshiBalasubramaniyam** [comment]
@Suchitra-Sahoo, Thank you for your consideration.

**Pull request merged**
