### PR TITLE
update cart and added empty state as well validations

### LINKED ISSUE #1162: Feat: Redesing cart
### Describe the feature

@Suchitra-Sahoo 

i would like to work on redesign cart ui

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

@Suchitra-Sahoo 

Feat: Redesing cart #1162

close #1162

## Description
[Please include a brief description of the changes or features added]

- added cart ui and make it fully functionals

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

Uploading Agricultural Tools Store — Mozilla Firefox 2024-07-18 09-38-04 (online-video-cutter.com).mp4…

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

kindly please check this and merge it
if you think my code is good enough to get `level 3` please assign me

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo

kindly please check this and merge it
if you think my code is good enough to get level 3 please assign me

**Comment by Suchitra-Sahoo** [comment]
attach screenshot of your changes

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

check this,

image

image

button is disable if there is no item in the cart

image

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo

kindly please check this and merge it
if you think my code is good enough to get `level 3` please assign me

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

kindly assign level please

**Comment by Suchitra-Sahoo** [comment]
image
The increment and decrement option is not aligned properly, also improve the design of increment and decrement button as you did for checkout.

**Comment by dhruv8433** [comment]
ok

**Pull request merged**
