### PR TITLE
Updated the chatbot with Visible close button, better styling and size

### PR DESCRIPTION
**Pull request by sau-mili**
Please check.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Add screenshots of the changes made. Mention your issue number too.

**Comment by sau-mili** [comment]
Screenshot 2024-05-11 010101
Screenshot 2024-05-11 010117
Here are the screenshots

**Comment by Suchitra-Sahoo** [comment]
issue #22

**Comment by sau-mili** [comment]
Hi, can you please add a level tag as well? for this is my first merged pull request of gssoc 2024.

**Pull request merged**
