### PR TITLE
Styled feedback button

### LINKED ISSUE #479: IMPROVE FEEDBACK BUTTON STYLING AND INCREASE MESSAGE AREA
### Describe the feature

Change CSS properties to style the feedback button 
Expanded the message area

### Add ScreenShots

before:
before
after:
after
updated:
[
updated version

Please Assign it to me 
Thank you @Suchitra-Sahoo 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ayushkrrana**
## Related Issue
IMPROVE FEEDBACK BUTTON STYLING AND INCREASE MESSAGE AREA

## Description
Change CSS properties to style the feedback button
Expanded the message area

## Type of PR

- [x] Feature enhancement

## Screenshots / videos (if applicable)
before : 
before
after:
after

updated :
updated version

Please Have a look , i have done changes according to you

## Checklist:
- [ X ] I have performed a self-review of my code
- [ X ] I have read and followed the Contribution Guidelines.
- [ X ] I have tested the changes thoroughly before submitting this pull request.
- [ X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

Please Consider Merging my pull request @Suchitra-Sahoo 

closes #479

### CODE REVIEW

**Comment by ayushkrrana** [comment]
Please assign it to me, i will try to improve it

**Comment by ayushkrrana** [comment]
> Its not looking suitable. Please work on improving it.

@Suchitra-Sahoo please see the changes i have updated the changes and now it look suitable and more concise 
Please Assign it to me
Thank You

**Comment by Suchitra-Sahoo** [comment]
Do attach a screenshot

**Comment by Suchitra-Sahoo** [comment]
Can you design something like this 
image

**Comment by ayushkrrana** [comment]
> Do attach a screenshot

i already attached it , you can see above @Suchitra-Sahoo

**Comment by ayushkrrana** [comment]
> Can you design something like this image

yes i will try

**Comment by ayushkrrana** [comment]
> Do attach a screenshot

I Have also uploaded above in the Screen Shot section
Please have a look
Thank you @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
Keep the design and shapre of contact us same as it is now. Design the feedbach button in such a way that it matches website design you can keep it same as chatbot colour

**Comment by Suchitra-Sahoo** [comment]
> > Keep the design and shapre of contact us same as it is now. Design the feedbach button in such a way that it matches website design you can keep it same as chatbot colour
> 
> Please Check it, I have done it @Suchitra-Sahoo

I think you have made some changes in contact us section as the message area has enlarged and other section has become small. Remove those changes.

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts too

**Comment by ayushkrrana** [comment]
Ok i will do ASAP

**Comment by Suchitra-Sahoo** [comment]
I'm closing this PR now once you are done with the changes raise another PR. Do attach a screenshot and mention your issue number.

**Comment by ayushkrrana** [comment]
> I'm closing this PR now once you are done with the changes raise another PR. Do attach a screenshot and mention your issue number.

I am done with the changes, please check my new PR #554 @Suchitra-Sahoo

**Pull request closed without merging**
