### PR TITLE
Fixed the Blog page and Home page Navbar Elements

### PR DESCRIPTION
**Pull request by deepak00944**
## Related Issue
None

## Description
As mentioned in issue https://github.com/Suchitra-Sahoo/AgriLearnNetwork/issues/732 the elements of the blog navbar and home navbar are not correctly positioned. I have fixed that issue for both pages the supporting screenshots are attached below. Kindly review this and let me know if I can add more things.

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

**BEFORE HOME PAGE**

Before the login button was not at its place which is now fixed.

image

image

**AFTER HOME PAGE**

Login button and Register button are now clearly visible.

Screenshot (615)

Screenshot (617)

**BEFORE BLOG PAGE**

image

**AFTER BLOG PAGE**

Screenshot (616)

**Video for mobile**

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/119965267/199a4942-daf0-47d7-b44b-ae5df1614265

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts

**Comment by deepak00944** [comment]
I have tried from my side I don't even know why it is showing that conflict I have everything. If possible please comment that particular line it will be solved

**Comment by Suchitra-Sahoo** [comment]
Pull all changes from origin

**Comment by Suchitra-Sahoo** [comment]
And then raise another PR.

**Comment by deepak00944** [comment]
I have raised another PR #854 kindly review it and label it under "gssoc" with level.

**Pull request closed without merging**
