### PR TITLE
Fixed the overlapping on scroll of login page.

### PR DESCRIPTION
**Pull request by meetarora10**
## Related Issue
Solved the issue #904

## Description
I have fixed the overlapping problem of the login page and the main container is now properly aligned on scroll as well.

## Type of PR

- [x] Bug fix
- [x] Feature enhancement

## Screenshots / videos (if applicable)

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143121854/1e34dfc6-a10b-4975-a2a5-f280053f388d

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
After merging your branch i can see the footer has got disturbed.

**Comment by Suchitra-Sahoo** [comment]
image

**Comment by meetarora10** [comment]
Yes I have changed the footer a little bit so that the main component is properly aligned in the middle.

**Comment by meetarora10** [comment]
So what I have to do now

**Comment by meetarora10** [comment]
@Suchitra-Sahoo please give the appropriate labels for this PR.

**Pull request merged**
