### PR TITLE
added search bar for blogs

### PR DESCRIPTION
**Pull request by Ishaparte**
pr1

Created a search bar feature for blogs for issue #133.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
I think you have not pulled the changes from origin as recently the blog section has been updated.

**Comment by Ishaparte** [comment]
I have pulled it now but I can still see only three blogs and below that there are images.
issue

**Comment by Suchitra-Sahoo** [comment]
There is some issue on your side. If you go and check the website through the link provided you may see the changes.

**Comment by Ishaparte** [comment]
fixed.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/113294672/4a4a49c3-5063-49be-8185-44ca29b8f4be

**Comment by Suchitra-Sahoo** [comment]
Make a change that suppose the user searches a specific blog then the shape of the card shouldn't change even if there is a single result.

**Comment by Ishaparte** [comment]
@Suchitra-Sahoo I am working on this issue.

**Pull request closed without merging**
