### PR TITLE
[feature]Product page Improvement

### LINKED ISSUE #1041: Feat: Improve Buy product page UI
### Describe the feature

- Add search bar
- make texts more visible
- make cart modal theme match with parent website

### Add ScreenShots

Screenshot 2024-07-01 135530

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by sau-mili**
## Related Issue
closes #1041 

## Description
[Please include a brief description of the changes or features added]
## Overall Product Page improvement: 
- Added JSON file to store product data
- Added highlights section
- On hover highlights about products appear
- Added JS to fetch data and display through HTML
- Added Search Bar
- Modified Cart UI
- Improved visibility of texts

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [x] Other (specify): addition of json file

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## BEFORE
image
## AFTER
image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
On adding a product the price is not increasing in cart. Same highlight is written for all the products. Search bar is also not working.

**Comment by sau-mili** [comment]
I haven’t worked on existing backend. I don’t have that skill. I only worked on Database part and Frontend

**Comment by sau-mili** [comment]
Can you please assign the labels?

**Comment by Suchitra-Sahoo** [comment]
But you can see that the cart was showing the total price on adding items but after merging your branch the amount is showing 0 only. Also as the search bar is not working so don't add it. I can see you have added option to like a product but on clicking it it is not working. And all the products can't have same highlights too.   

I have not integrated any backend yet to the project it is entirely frontend based so where are you facing issues?

**Comment by sau-mili** [comment]
I will try to check these issues, and consult you if required.

**Comment by sau-mili** [comment]
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/146661411/dabcba40-e9ae-4955-a7fb-c50b9894ec44

I just checked and it is working completely,

**Comment by Suchitra-Sahoo** [comment]
pull all the changes from origin and make other corrections too as mentioned in previous review.

**Comment by sau-mili** [comment]
okay

**Pull request merged**
