### PR TITLE
Added changes as per issue #1206

### PR DESCRIPTION
**Pull request by Unnimaya6122004**
## Related Issue
Issue #1206 

## Description
Added changes required

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot from 2024-07-28 04-05-23

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
NIL

### CODE REVIEW

**Comment by Unnimaya6122004** [comment]
can u pls check this PR

**Comment by Suchitra-Sahoo** [comment]
Can you set the size of images as same. You nay reduce the content accordingly.

**Comment by Unnimaya6122004** [comment]
Mam,I think this image is good fit and clear for the content

**Comment by Unnimaya6122004** [comment]
Is it required to reduce the content...

**Pull request merged**
