### PR TITLE
I have added an aesthetic seedling mouse follower 

### PR DESCRIPTION
**Pull request by Shadyx6**
The seedling mouse follower gives the website's UX an upper hand, I am contributor of GSSoC, I used my svg and javascript knowledge to create this awesome mouse follower
Heres how it looks like- (it feels even better on scrolling)
Screenshot (126)

### CODE REVIEW

**Comment by Shadyx6** [comment]
merging mouse follower seedling

**Comment by Suchitra-Sahoo** [comment]
Mention your issue number. It will be better if you can add a video to see your changes.

**Comment by Shadyx6** [comment]
Can u check it please @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
I can see issue 145 is assigned to someone else. You need to raise your issue and the make a PR with it.

**Comment by Suchitra-Sahoo** [comment]
Also It would better if you can improve the design of the mouse follower.

**Comment by Shadyx6** [comment]
Okay I'll make another issue and I'll try to improve the design

**Pull request closed without merging**
