### PR TITLE
checkout page added with fully functionality

### PR DESCRIPTION
**Pull request by Varsani2520**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
checkout page missing 

## Description
[Please include a brief description of the changes or features added]
1.checkout page added
2.design the payment ui
3.add functionality like product show 
4.click on make payment button then redirect buy_product page

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Varsani2520** [comment]
@Suchitra-Sahoo ,check it 
#982

**Comment by Suchitra-Sahoo** [comment]
can you add some more payment methods in this?

**Comment by Varsani2520** [comment]
Yes @Suchitra-Sahoo ,tell me what you want

**Comment by Suchitra-Sahoo** [comment]
You can add more methods like credit card, debit card and many more. Also the summary of order should be visible when the user enters checkout page instead of when he clicks the payment method.

**Pull request merged**
