### PR TITLE
Fixed the login page

### PR DESCRIPTION
**Pull request by meetarora10**
## Related Issue
Solved the issue #904
## Description
I have fixed the login page and now the contents are properly aligned on the screen.
## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot (488)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Don't reduce the size. The problem is still there as when we scroll up it overlaps the navbar.
image

**Comment by meetarora10** [comment]
@Suchitra-Sahoo please give gssoc and appropriate level labels.

**Comment by meetarora10** [comment]
> Don't reduce the size. The problem is still there as when we scroll up it overlaps the navbar. image

So should I do another commit?

**Comment by Suchitra-Sahoo** [comment]
I can give you level tag on your final PR so resolve the issue and make another PR. This PR has been reverted.

**Comment by meetarora10** [comment]
Ok I will do another PR

**Pull request merged**
