### PR TITLE
Scroll up position update

### PR DESCRIPTION
**Pull request by hars-21**
Successfully updated scroll up position to center.
#173 fixed

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
This branch has conflicts

**Comment by Suchitra-Sahoo** [comment]
add some screenshots to see your changes

**Comment by hars-21** [comment]
Screen Shot 2024-05-16 at 6 53 57 PM

**Comment by hars-21** [comment]
@Suchitra-Sahoo Please review

**Comment by Suchitra-Sahoo** [comment]
Why your navbar is so disturbed. I have hust checked and everything is fine.

**Pull request closed without merging**
