### PR TITLE
Modified navbar of the AgroBlogs page.

### PR DESCRIPTION
**Pull request by meetarora10**
## Related Issue
Solves #1006

## Description
Now the navbar on the agro blogs page is similar to other pages with properly working hamburger icon.

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot (544)
Screenshot (545)
## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by Suchitra-Sahoo — APPROVED** [review]

**Comment by Suchitra-Sahoo** [comment]
Hamburger menu option is not working on clicking.

**Comment by meetarora10** [comment]
@Suchitra-Sahoo it is working

**Comment by Suchitra-Sahoo** [comment]
Screenshot 2024-06-29 115232
Screenshot 2024-06-29 115242
Also the navbar options are overflowing.

**Comment by meetarora10** [comment]
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143121854/9d393473-d10b-452d-ab1e-c9a48a5ca428

**Comment by meetarora10** [comment]
@Suchitra-Sahoo hamburger menu is working fine.

**Comment by meetarora10** [comment]
Please don't revert this PR 
If you say I will create another issue to fix the navbar overflowing options.

**Comment by meetarora10** [comment]
Hi @Suchitra-Sahoo  can you tell me what to do for this issue.

**Pull request merged**
