### PR TITLE
Fixes Issue #162 Improved UI/UX agro blogs section

### PR DESCRIPTION
**Pull request by dhanushsurendra**
The new design makes the section look visually appealing, responsive, and better than the previous one.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts of this branch. After that add some screenshots to see your changes.

**Comment by dhanushsurendra** [comment]
Screenshot 2024-05-12 221734

This is the updated agro blogs section.

**Comment by Suchitra-Sahoo** [comment]
whats your issue number?

**Comment by dhanushsurendra** [comment]
#162

**Comment by dhanushsurendra** [comment]
Could you please add GSSoc'24 and level label to this issue?

**Comment by Suchitra-Sahoo** [comment]
@dhanushsurendra I had to revert back your PR because if you go and check the link of the website you will see that the home page has been updated but merging your branch removes all those changes. Look into it and raise another PR.

**Comment by dhanushsurendra** [comment]
Alright

**Pull request merged**
