### PR TITLE
Modified the Blog-card design According to issue

### PR DESCRIPTION
**Pull request by sau-mili**
Issue number [#268 ](url)

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
add some screenshots to see your changes.

**Comment by sau-mili** [comment]
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/146661411/9f523aff-8aab-40f3-9e17-828ee07ccc93


screenrecorded.

**Comment by sau-mili** [comment]
@Suchitra-Sahoo please check

**Comment by sau-mili** [comment]
fixes #268

**Comment by Suchitra-Sahoo** [comment]
But on hovering the card it changes back to same colour only. It will be better if you can design something like this 
Screenshot 2024-05-16 211659
You can also create a seperate blog page and all the blogs there. And when the user clicks on the blog icon on navbar he can be directed to the blog page.

**Comment by sau-mili** [comment]
Okay, I will do this.. should I make a new issue for this? This might take a day or two to make.. till then it will be easy if you could merge this for now maybe, and I create a new issue and work on that for the time.

**Comment by Suchitra-Sahoo** [comment]
You may raise another PR under the same issue. Once done add screenshots and then i'll check and merge.

**Pull request closed without merging**
