### PR TITLE
payment method added in checkout page

### PR DESCRIPTION
**Pull request by Varsani2520**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
#1167 

## Description
[Please include a brief description of the changes or features added]
i added  paypal as well as credit card as a payment method
## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
image

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Varsani2520** [comment]
@Suchitra-Sahoo ,review it and if you want to any changes then inform me

**Comment by Suchitra-Sahoo** [comment]
The total price should be in Rs also on clicking make payment direct  it back to product page.

**Comment by Varsani2520** [comment]
ok @Suchitra-Sahoo

**Comment by Varsani2520** [comment]
Hey @Suchitra-Sahoo ,check #1237

**Pull request merged**
