### PR TITLE
newsletter is added in footer

### PR DESCRIPTION
**Pull request by Srujitha-Raghava**
## Related Issue
#482 

## Description
Included newsletter feaature in the footer of the webpage with validation

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot 2024-05-28 104858

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
It is looking a little congested. Give proper spacing. Also in screenshot take entire view of the footer. Keep the colour of subscribe button as dark green as in background.

**Comment by Suchitra-Sahoo** [comment]
Once you are done do inform me

**Comment by Srujitha-Raghava** [comment]
@Suchitra-Sahoo mam,do check this
Screenshot 2024-05-29 104700

**Comment by Suchitra-Sahoo** [comment]
Yes its good raise PR

**Comment by Suchitra-Sahoo** [comment]
pull all changes from origin

**Pull request closed without merging**
