### PR TITLE
Fixed the broken links in the footer section of Blog Page!

### PR DESCRIPTION
**Pull request by Samridhi002**
## Description
I have added correct links in the "Resource Library" and "Contact us " section of the footer page. Now on clicking them, they navigate to their respective sections on the home page.

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

hey PA,
Please review the updated code and merge it. Thank You!

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
About us link is not working

**Comment by Samridhi002** [comment]
> About us link is not working

I'll make the changes.
Do I have to push the changes on the same branch or should I make a new branch?

**Comment by Suchitra-Sahoo** [comment]
do in same just raise another PR and pull all changes

**Comment by Samridhi002** [comment]
> do in same just raise another PR and pull all changes

Ok

**Pull request merged**
