### PR TITLE
Added "Terms and Conditions" and "Privacy Policy" Pages 

### LINKED ISSUE #1077: 🌟Feature : Add "Terms and Conditions" and "Privacy Policy" Pages
### Describe the feature

Hey @Suchitra-Sahoo 
i want to create and add two separate pages in the website's footer by adding links to two new pages: 
Terms and Conditions and Privacy Policy. 
These pages are essential for informing users about the legal aspects of using our site and ensuring compliance with privacy regulations.

**What will i do**
1. Create Terms and Conditions Page
 - Develop a new page titled "Terms and Conditions."
- Include comprehensive terms that cover the use of our website, user responsibilities, limitations of liability, and other relevant legal 

2. Create Privacy Policy Page
- Develop a new page titled "Privacy Policy."
- Detail how we collect, use, and protect user data.

3. Update Footer
- Add links to the newly created "Terms and Conditions" and "Privacy Policy" pages in the website's footer.

This is where we can add the links to navigate to the respective pages.
image

Could you Please assign me this issue under GSSoC'24 ?

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @Suchitra-Sahoo,
issue closes #1077 

### Here's What I Did -
1. **Added a Dedicated "Terms and conditions"** Page
2. **Added a Dedicated "Privacy Policy"** Page
3. I **tried my best to style the pages** to follow the website's theme
4. **Added Navigating Links** to the Footer **with Hovering Effect.**
5. I Integrated the **footer at the bottom** and **Navbar at the top**

Here's are the Results -

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/131389695/e6c51a17-b845-44aa-a476-4396156c3846

Please take a look and review it.

## Type of PR
- [x] Feature enhancement

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by aslams2020** [comment]
@Suchitra-Sahoo PLeaase review it.

**Comment by Suchitra-Sahoo** [comment]
Don't add the terms and conditions pages write now. It will be created later.

**Comment by aslams2020** [comment]
@Suchitra-Sahoo , So should I remove the "Terms and conditions" Page for now? and keep "Privacy Policy" In this PR.
Later, When there's a need for "Terms and conditions" Page I will send the PR.

**Comment by Suchitra-Sahoo** [comment]
Okay let both of them br there just make sure the text is visble clearly so choose some other colour. And make sure after adding privacy policity and terms & condition the footer should be responsive for all screen sizes

**Comment by aslams2020** [comment]
@Suchitra-Sahoo Sure, I will do it

**Comment by aslams2020** [comment]
@Suchitra-Sahoo Done!.. I've made the Text colors to be readable and Also the Footer is Responsive!
Please Check.

**Comment by Suchitra-Sahoo** [comment]
Please update the footer in all the sections.

**Comment by Suchitra-Sahoo** [comment]
Also in privacy & terms and condition page the home option of navbar is not working so fix it.

**Comment by aslams2020** [comment]
@Suchitra-Sahoo Sure.! Doing it now

**Comment by aslams2020** [comment]
> Also in privacy & terms and condition page the home option of navbar is not working so fix it.

Oh ok. thanks for clarifying

**Comment by Suchitra-Sahoo** [comment]
ok do it then i'll give level2

**Comment by Suchitra-Sahoo** [comment]
one more thing the cards are almost toiching the footer so correct it too there should be some space.

**Comment by aslams2020** [comment]
Sure @Suchitra-Sahoo , Before that will you revert the merged PR? So that i can Push the updated code to the main branch

**Comment by aslams2020** [comment]
> ok do it then i'll give level2

Done @Suchitra-Sahoo , Please review the new PR.
Thankyou!

**Pull request merged**
