### PR TITLE
Enhancement of Contact Us Page UI according to your inputs

### PR DESCRIPTION
**Pull request by Arnavsao**
## Related Issue
Enhancement of Contact Us Page UI according to your inputs

## Description
Revamped the Contact Us page UI to improve user experience and aesthetics.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Before:
Screenshot 2024-05-24 at 12 14 32 PM

After:
Screenshot 2024-05-24 at 12 46 07 PM

Assigned https://github.com/Suchitra-Sahoo/AgriLearnNetwork/issues/462 to @Arnavsao.

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Improving the design a little more. Also please make the feedback button larger.

**Comment by Arnavsao** [comment]
Hello Suchita,
I have made some changes I hope you will like it. I’m not sure about you get the code or not. Let me know do you like it or not. 
I think it looks much better and visible than previous one and goes with the rest of the website
￼

**Comment by Suchitra-Sahoo** [comment]
add a screenshot

**Comment by Arnavsao** [comment]
Screenshot
￼

**Comment by Suchitra-Sahoo** [comment]
I can't see the screenshot

**Comment by Arnavsao** [comment]
Is it visible now Suchitra?

**Comment by Suchitra-Sahoo** [comment]
No its not visible. Paste your screenshot in PR not in the issue.

**Comment by Suchitra-Sahoo** [comment]
Pull all changes from origin and resolve the conflicts

**Comment by Suchitra-Sahoo** [comment]
I'm closing this PR, once you are done with the changes raise another PR

**Pull request closed without merging**
