### PR TITLE
Add/Allow google Login #762

### PR DESCRIPTION
**Pull request by K-Svayam05**
## Description
The Feature of Google Login is added on the Login Page(login.html)

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Since there is no Backend or Database connected to this website, this button will just allow to login and will redirect to home page without storing the details of the google account.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
both login and sign in with google are overlaaping. Is the sign in with google functioning or you have just added a button?

**Comment by Suchitra-Sahoo** [comment]
mention issue number

**Comment by Suchitra-Sahoo** [comment]
Make corrections in spacing

**Comment by K-Svayam05** [comment]
> Make corrections in spacing

Okay, on it!

**Comment by K-Svayam05** [comment]
> Make corrections in spacing

image
Done the adjustments and spacing

**Comment by Suchitra-Sahoo** [comment]
It is looking like this
image

**Comment by K-Svayam05** [comment]
@Suchitra-Sahoo Could you please add level to this task under GSSoC so that I could get my credits for accomplishing this task.
Thank you!

**Pull request merged**
