### PR TITLE
Fixes #324 : Parallax effect on homepage

### LINKED ISSUE #324: Feat: Parallax effect on the homepage
### Describe the feature

Right now, the website looks too simple, containing the carousel in the Home page only.

### Add ScreenShots

I want to add Parallax effect to the website, so that it ensures a great User experience as well as it increases the attractiveness of the website.

 
Screenshot 2024-05-16 183810

Kindly assign me this issue under GSSoC '24.
Thank you!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Sambit-Mondal**
Added a Parallax effect to the Homepage, thus improving the overall UI of the homepage.

Proof:

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/138088550/c0c460b4-64fb-428e-a8e9-a7fb1616e506

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
How come the navbar is looking so disturbed. I have just checked and on my side its totally fine.

**Comment by Sambit-Mondal** [comment]
@Suchitra-Sahoo Mam I've created an issue regarding that. The navbar isn't completely responsive. And this disturbance appears when we view the webpage in screens, having width between 900px and 1100px.
Kindly refer to Issue #325 .

Thank you!

**Comment by Sambit-Mondal** [comment]
@Suchitra-Sahoo Kindly have a look mam.

**Comment by Suchitra-Sahoo** [comment]
Okay try it now. I guess the issue is resolved.

**Comment by Sambit-Mondal** [comment]
Okay, sure!

**Pull request closed without merging**
