### PR TITLE
Solving issue #321 by adding Carousel Component.

### PR DESCRIPTION
**Pull request by VarshaKammari**
Carousel Component is added to provide the functionality of slide-show. Added Bootstrap cdn link to use bootstrap components. After adding the bootstrap link there is slight change in the font-size and font-weight in different headings in the website. So, in order to have previous view of font-weight and font-size of headings, i added font-weight and font-size to some of the headings accordingly.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Add a video to demonstrate your changes.

**Comment by VarshaKammari** [comment]
Here is a video demonstrating the changes that, I made in the code.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114400934/cbff6555-35ed-41cf-9fd6-538c985e8294

**Comment by Suchitra-Sahoo** [comment]
I think you have not pulled changes from origin because if you go and check the about section of the website through given link you will see its updated.

**Comment by VarshaKammari** [comment]
Okay @Suchitra-Sahoo,I will pull the changes from origin and add the assigned functionality.

**Pull request closed without merging**
