### PR TITLE
#763 : Add input field for re-enter password. Add validation to email and password fields in signup page.

### PR DESCRIPTION
**Pull request by RanjanaShenoy**
Issue: #763 

## Description
Add input field to enter phone number, re-enter password. Add validation to email, phone and password fields in signup page.

## Type of PR

- [X] Feature enhancement

## Screenshots / videos (if applicable)

image

image

image

image

image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

There was mistake in: 
messages were swapped for signup and signin page. 
 signup page -> 'welcome back' message instead of 'Hello Friend'. 
for signin page -> 'Hello Friend' message instead of 'welcome back'.

An existing user should be welcomed as 'welcome back'. Hence, Corrected that as:
signup page -> 'Hello Friend'
signin page -> 'welcome back'

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
remove phone number option and add and an option to hide and view the password

**Comment by RanjanaShenoy** [comment]
@Suchitra-Sahoo , I have a doubt. After making code changes, should I push code changes to this PR itself or create a new one?

**Comment by Suchitra-Sahoo** [comment]
you can push to this PR

**Comment by Suchitra-Sahoo** [comment]
Is it done?

**Comment by RanjanaShenoy** [comment]
Hi @Suchitra-Sahoo ,
It is done.

**Pull request merged**
