### PR TITLE
Resource library

### PR DESCRIPTION
**Pull request by dhruv8433**
@Suchitra-Sahoo 

please check this and merge it

## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

Feat: Add Detailed page for resource library #501

## Description
[Please include a brief description of the changes or features added]
- i updated our index page and only show there 3 resourece cards
- added one button under that `see more`
- when useer click on that we redirect them to `/resource-library` page

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

home page `/index`

image

when user click on `see more ` button we redirect them to `/resource-library`

route `/resourse-library`

image

in responsive

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Hey kindly attach a video to demonstrate your changes. Also have you checked whether all components are clearly visible and aligned for small devices also?

**Comment by Suchitra-Sahoo** [comment]
Recently some changes in navbar have been merged so pull all of them from origin

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

now you can merge it

**Comment by Suchitra-Sahoo** [comment]
Before merging I want you to attach a video too so that in case there is some changes i can tell you rather than merging and reverting back again.

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

here is video of that

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114583978/05b68708-4f8d-4769-8ddb-39efacbef775

**Comment by Suchitra-Sahoo** [comment]
Instead of keeping just 3 videos on main page seperately create page for resource library. And the shape of the card should be even from all sides. If you go and check the websit link you will find when we hover on the card then youtube video slides up so that the user can also see the video within the card as well as on youtube. So keep that same. And pull all changes too.

**Comment by Suchitra-Sahoo** [comment]
Also improve the background.

**Comment by dhruv8433** [comment]
ok i will do that

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

check this out
home page now look like

image

when user click on navigation link `resource library` they will redirected to `/resource-library` 
and when we hover on the card then youtube video slides up so that the user can also see the video within the card as well as on youtube.

as you said,
 
image

**Comment by Suchitra-Sahoo** [comment]
I think you have done some changes in contact us like "submit query" and dropdown in mobile no so remove them.

**Comment by dhruv8433** [comment]
No, i don't even touch contact us code 

my `index.html`'s contact us is same as upstream `main`'s contact us

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

kindlty please check this and response

**Comment by Suchitra-Sahoo** [comment]
can you add something in right also as it is looking empty
image

**Comment by Suchitra-Sahoo** [comment]
@dhruv8433 I had to revert back your PR as the resource library page is not linking properly.Kindly check on it.
image

**Pull request merged**
