### PR TITLE
Fixed navbar issue

### PR DESCRIPTION
**Pull request by dhairyagothi**
## Related Issue
#799 

## Description
Fixed navbar CSS in mobile view

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Before:
image

After :
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@Suchitra-Sahoo please add gssoc label also

**Comment by Suchitra-Sahoo** [comment]
It has not changed

**Comment by dhairyagothi** [comment]
image

it is working fine on local host

**Comment by dhairyagothi** [comment]
should i make a new PR ?

**Comment by Suchitra-Sahoo** [comment]
But on my side its looking like this only.

**Comment by dhairyagothi** [comment]
> But on my side its looking like this only.

I think there is some problem in merge 



The changes i have made is not changed in repo files

**Comment by dhairyagothi** [comment]
please check PR #822

**Comment by dhairyagothi** [comment]
please add gssoc label in PR 
unless it will not be counted as contribution

**Comment by dhairyagothi** [comment]
@Suchitra-Sahoo Please add Gssoc label Mam

**Pull request merged**
