### PR TITLE
add hovering effect in social icons

### LINKED ISSUE #1047: Feat:Add actual colour hovering effect on footer .
### Describe the feature

when we hover over the social icon it will be in its actuqal colour . 

### Add ScreenShots

before  : 

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/159682348/686a5a05-e1af-46bf-9b43-f5f9b7ba5d7a

Want to make it like this : 

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/159682348/9797d785-963d-4dcd-8f07-681583879dd0

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ANKeshri**
## Related Issue
fixes #1047 

## Description
on hovering it changes to its actual colour IN ALL THE PAGES OF THE WEBSITE .

## Type of PR

- [X] Feature enhancement

## Screenshots / videos (if applicable)

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/159682348/201bc6e4-3540-4195-95da-2c87ff3fea29

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts. Pull all changes from origin.

**Comment by ANKeshri** [comment]
> Resolve the conflicts. Pull all changes from origin.

working on it

**Comment by Suchitra-Sahoo** [comment]
in blog page on hovering the email option it shows green colour

**Comment by ANKeshri** [comment]
@Suchitra-Sahoo you have not given level for it and for blog page shoud i create new pr to change email option?

**Comment by ANKeshri** [comment]
@Suchitra-Sahoo i vae createted new pr and fixed the mail of blog page please review and give level to this pr . Thank you

**Pull request merged**
