### PR TITLE
Enhanced Feedback form

### LINKED ISSUE #451: Feat:Enhancing FeedBack form
### Describe the feature

To redesign and enhance the feedback form on your website to create a more visually appealing and user-friendly experience. My goal is to improve user interaction and satisfaction by implementing a modern UI design.Please assign me this task.

### Add ScreenShots

no

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by kashisharora9462**
Enhance the ui of feedback form and make it user friendly and more appelaing.

## Related Issue
fixes #451 

## Description
I have improved the styling of your website's feedback form, enhancing its overall appearance. Additionally, I have added hover effects and smooth transitions to make it more visually appealing and engaging for users.

## Type of PR

- [x] Feature enhancement

## Screenshots / videos (if applicable)
Screenshot 2024-05-24 102559

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by kashisharora9462** [comment]
@Suchitra-Sahoo please check and merge it with main repository to make it better.

**Comment by Suchitra-Sahoo** [comment]
Please improve it. Previous one was looking much better. You can refer other websites to get idea about feedback forms.

**Comment by kashisharora9462** [comment]
> Please improve it. Previous one was looking much better. You can refer other websites to get idea about feedback forms.

Okay sure sir!

**Comment by kashisharora9462** [comment]
I have made changes and I hope now you like them. Please let me know if you need any further changes.
Screenshot 2024-05-26 073902

**Comment by kashisharora9462** [comment]
Please reply as soon as possible if you want some other changes so that i can start working on other issue that you had assigned to me.

**Comment by kashisharora9462** [comment]
I had changed the format and made it better. Please check it and let me
know if you need other changes. Please reply as soon as possible, it will
just take a few minutes to check and reply.

**Comment by Suchitra-Sahoo** [comment]
@kashisharora9462 keep it in green shade

**Comment by kashisharora9462** [comment]
changed

**Comment by kashisharora9462** [comment]
Done.

**Comment by Suchitra-Sahoo** [comment]
Your screenshot is not visible to me

**Comment by kashisharora9462** [comment]
Please check now.

**Comment by Suchitra-Sahoo** [comment]
image
Its not working. As soon as the website loads it appears like this

**Comment by kashisharora9462** [comment]
> image Its not working. As soon as the website loads it appears like this

I cannot understand your query.As soon as website load ,it looks a feedback form ,can you please tell your query in detail.

**Comment by Suchitra-Sahoo** [comment]
You can see in attached screenshot the alignment of footer is totally disturbed. The feedback form pops up suddenly as soon as website opens.

**Comment by kashisharora9462** [comment]
I had resolved that issue .Please check again

**Pull request merged**
