### PR TITLE
chat bot updated

### PR DESCRIPTION
**Pull request by nagamukesh**
I have updated the chatbot using bot press plug-in

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/112798996/7dccbbcf-5f54-433d-bb65-1727eb7dd3e4

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/112798996/dfca9884-e438-47e3-97a5-6b1c5b1d3f07

The above videos show the working of the chatbot

Thanks @Suchitra-Sahoo for giving me this oppurtunity

### CODE REVIEW

**Comment by nagamukesh** [comment]
This repo have no conflicts at the time of pulling this request

**Comment by Suchitra-Sahoo** [comment]
@nagamukesh the functioning part of the bot is fine. But if you go and click on the website link given in the repo you will see it has a yellow and green theme. Also the closing option is visible and is not hidden by the navbar and insteas of B the bot has A which represents agribot.

**Comment by nagamukesh** [comment]
I have changed the color code
image
image
now, this is how the bot looks like
image
now, the close button is also visible 
suggest any potential changes. If not, merge this request
thank you

**Comment by Suchitra-Sahoo** [comment]
There are conflicts in this branch. I can't merge your PR before you solve it.

**Comment by nagamukesh** [comment]
you have accepted/merged a pull request where someone else added a chatbot which is again not working, which is why it is conflicting.
I request to revert those changes as soon as possible so that I can make sure my changes do not conflict

**Comment by nagamukesh** [comment]
I request to look into this pull request and please revert those changes done to chat bot which are causing conflicts with my pull request

**Comment by Suchitra-Sahoo** [comment]
You may pull the changes from origin and raise another PR. Attach a video to showcase how your bot is functioning better as compared to current bot. Based on that your PR will be merged.

**Pull request closed without merging**
