### PR TITLE
Backend to login/signup

### PR DESCRIPTION
**Pull request by sharmi4590**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
Solved #632 

## Description
[Please include a brief description of the changes or features added]
I have made the backend for the login and signup page. 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

I have covered everything in the video .
-> It throws error if duplicate user email is being registered.
-> It throws error if wrong password is given.
-> The password must be more than 6 characters.
-> The username takes place according to its email. for example if user email is sha@gmail.com then the username "sha" will be displayed.
-> Logout button is also there.
-> If the user has previous login credintials in there local storage they will redirect automatically.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/102676949/c66b8eab-0817-4887-8ef2-f95b03bb4bf7

For sharmi4590@gmail.com
Screenshot 2024-06-05 170226

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]
If you want the data to be in your firebase account make sure to replace the credentials.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
The navbar looks like this after login alignment is not proper
image
image
logout option is overlapping and is not looking good

**Comment by sharmi4590** [comment]
@Suchitra-Sahoo Okay I will do the changes.

**Comment by sharmi4590** [comment]
Please assign the labels also.

**Comment by sharmi4590** [comment]
Hey why had you reverted it and also backend is not working do I have to do it again?

**Comment by sharmi4590** [comment]
@Suchitra-Sahoo It took me a lot of time to do that and simply u have not assigned any labels or not even passed any statements

**Pull request merged**
