### PR TITLE
#63 Added content and updated readme

### PR DESCRIPTION
**Pull request by AnushkaJainFirst**
### Additions:
- **Let's get started:** steps to contribute to a repository by forking, cloning, updating, add, commit, push, pull
- **Code of conduct:** 

### Additions:
Highlighting, underlining, font-size; etc of content given

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Mention issue number and add screenshots.

**Comment by AnushkaJainFirst** [comment]
Issue no: #63 
**Screenshots:**
read-1

read-2

read-3

read-4

@Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
Keep the readme as it is. Just add all the content of "lets get started" below overview section.

**Comment by AnushkaJainFirst** [comment]
> Keep the readme as it is. Just add all the content of "lets get started" below overview section.

Ok @Suchitra-Sahoo

**Comment by AnushkaJainFirst** [comment]
I have updated the readme.md like you said. You can now review and merge @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
Go and checkout the current readme. Code of conduct is not there in table of contents. Also don't change the heading. Keep evrything as it is just add lets get started below website overview.

**Comment by Suchitra-Sahoo** [comment]
Raise another PR there is some issue in this.

**Pull request closed without merging**
