### PR TITLE
checkout page completed

### PR DESCRIPTION
**Pull request by Varsani2520**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
#982 
## Description
[Please include a brief description of the changes or features added]
i added checkout page on checkout button click then show checkout page
## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Varsani2520** [comment]
@Suchitra-Sahoo ,review it

**Comment by Suchitra-Sahoo** [comment]
@Varsani2520 it is the frontend of checkout page so try to show the items which are added in cart and total amount shown in cart to reflect on payment page. And remove that paragraph below summary. Link the make payment option and submit option to direct back to the cart as right now there is no backend.

**Comment by Varsani2520** [comment]
Ok

**Comment by Varsani2520** [comment]
@Suchitra-Sahoo ,can you please 1 chance 

because my laptop is in fault so i dont have laptop few day ,now i have so please assign i completed within a day

**Comment by Suchitra-Sahoo** [comment]
@Varsani2520 I have just closed the PR you can raise another PR

**Pull request closed without merging**
