### PR TITLE
aling buttons

### LINKED ISSUE #1162: Feat: Redesing cart
### Describe the feature

@Suchitra-Sahoo 

i would like to work on redesign cart ui

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

@Suchitra-Sahoo 

Feat: Redesing cart #1162

close #1162

## Description
[Please include a brief description of the changes or features added]

- added cart ui and make it fully functionals

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

i fetched upstream and aling quantity buttons 
please add level 3 and merge it

image

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

I request you
Please check this and merge it
And give level 3 

I completed my task as you said

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

kindly please check this and merge it
if you think my code is good enough to get `level 3`
please assign it

**Comment by Suchitra-Sahoo** [comment]
The alignment issue is resolve but the checkout option is still working even if there is no products in cart. Also I asked to apply some style on increase and decrease button.

**Pull request merged**
