### PR TITLE
Update login.html - Added "Return Home" button

### PR DESCRIPTION
**Pull request by yeolesanskruti**
Redirected to Home Page from login and register page using "Return Home" button.

## Related Issue
Issue #628 

## Description
I added a "Return Home" button to the login and Register page below all details so that the user can return to the home page just by clicking on it. It enhances the user experience.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

LOGIN PAGE -
Screenshot 2024-06-01 183844

REGISTER PAGE -
Screenshot 2024-06-01 183811

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

Please review.
GSSoC'24

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Don't add return home within the form. Instead add navbar and footer in login page

**Comment by yeolesanskruti** [comment]
Okay @Suchitra-Sahoo. I will code and and update the PR.
Thank you.

**Comment by mehrun171** [comment]
> Don't add return home within the form. Instead add navbar and footer in login page

Reply to me mam and look forward for my pr...my pr didnt get uploaded in the leaderboard and i wasted my time on this.

**Comment by Suchitra-Sahoo** [comment]
> > Don't add return home within the form. Instead add navbar and footer in login page
> 
> Reply to me mam and look forward for my pr...my pr didnt get uploaded in the leaderboard and i wasted my time on this.

@mehrun171 what's your issue number?

**Comment by yeolesanskruti** [comment]
I have added the header and footer to login and registration page and code of files is updated accordingly in PR #640 itself.

Please review @Suchitra-Sahoo.

**Comment by mehrun171** [comment]
> > > Don't add return home within the form. Instead add navbar and footer in login page
> > 
> > 
> > Reply to me mam and look forward for my pr...my pr didnt get uploaded in the leaderboard and i wasted my time on this.
> 
> @mehrun171 what's your issue number?

389

**Comment by Suchitra-Sahoo** [comment]
> > > > Don't add return home within the form. Instead add navbar and footer in login page
> > > 
> > > 
> > > Reply to me mam and look forward for my pr...my pr didnt get uploaded in the leaderboard and i wasted my time on this.
> > 
> > 
> > @mehrun171 what's your issue number?
> 
> 389

@mehrun in your issue i have asked you your PR number too so kindly reply

**Comment by Suchitra-Sahoo** [comment]
@yeolesanskruti don't change the background just add navbar and footer. Also i can see login option is going out of screen.

**Comment by Suchitra-Sahoo** [comment]
Its not working. Its looking like this.
image

**Pull request merged**
