### PR TITLE
Responsive design

### PR DESCRIPTION
**Pull request by NitinChakrawarti**
Website is responsive to different devices you can easily navigate, nav  bar and home section.

**my issue no #158**

**Before making responsive: home section items are not visible completely .**

WhatsApp Image 2024-05-12 at 15 38 06_e2b3d57a
WhatsApp Image 2024-05-12 at 15 38 05_09d8aa93

**after making responsive:-**

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/149225785/8fda4233-c6e3-4c67-b2a7-596010ef3854

### CODE REVIEW

**Comment by NitinChakrawarti** [comment]
Now user can use website in different devices easily.

**Comment by Suchitra-Sahoo** [comment]
Resolve the conflicts of this branch.

**Comment by Suchitra-Sahoo** [comment]
Recently various PR has been merged so the home page designing is changed. You may look it by clicking the website's link. Make sure those changes are visible. Currently the video which you have sent, I can see it is showing the website with previous styling.

**Comment by NitinChakrawarti** [comment]
here is the responsive design with latest updates


https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/149225785/e2ded8e0-3bde-4f48-9dbd-703232212a23

**Pull request closed without merging**
