### PR TITLE
Added Tailwind And Effects on blog page

### PR DESCRIPTION
**Pull request by Mujtabaa07**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description
I added Tailwind and update contributing.md file with it and add effect on blog page and tansitions.

## Type of PR
#438 

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/70109255/96a8ba07-ae17-4ac0-b8de-40f5dac00c90

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
Why the cards of resource library are not even from all sides? I just checked and it is fine on my side.
image

**Comment by Mujtabaa07** [comment]
> Why the cards of resource library are not even from all sides? I just checked and it is fine on my side. image

I'll check it , but when I cloned the project it was like that only ,i didnt made any changes in resource library

**Comment by Mujtabaa07** [comment]
resource fix agri
its fixed

**Comment by Mujtabaa07** [comment]
> Why the cards of resource library are not even from all sides? I just checked and it is fine on my side. image

I had fixed it now it is similer 
Updated Resource Library similer to orginal

**Comment by Suchitra-Sahoo** [comment]
Why there is so much spacing between the cards? You can check the website through the link and do accordingly.

**Comment by Mujtabaa07** [comment]
> Why there is so much spacing between the cards? You can check the website through the link and do accordingly.
I had corrected it now 

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/70109255/675039df-5d0c-4d58-8789-423689eb5295

**Comment by Suchitra-Sahoo** [comment]
Hey can you just tell me do i need to install some packages to run this?

**Comment by Mujtabaa07** [comment]
> Hey can you just tell me do i need to install some packages to run this?


yes just "npm install" it install all packages which are reqiured 
and i had updated contributing.md file like how to install

**Comment by Suchitra-Sahoo** [comment]
Okay so i'll merge your PR tomorow itself and check if its working.

**Comment by Suchitra-Sahoo** [comment]
before that pls resolve the conflicts

**Comment by Mujtabaa07** [comment]
Yes sure

**Comment by Mujtabaa07** [comment]
> before that pls resolve the conflicts

resolved

**Comment by Suchitra-Sahoo** [comment]
Its not working. Even after installing all the packages it is showing errors. Also i think css file is not linking properly.
image

**Comment by Mujtabaa07** [comment]
Now I had raised pr and fix the issue , issue was while removing conflict
so line to were removed so , and first run “npm run build” it will check
all packages while are need to be loaded and the run”npm run dev”

**Pull request merged**
