### PR TITLE
Adjusted the font size of text for mobile screens.

### PR DESCRIPTION
**Pull request by sancharigandhi**
I have adjusted the font size of the texts to fit the screen size. Currently, I am working on removing the gap between the carousel and the about section video, as well as changing the backgrounds of other sections. Issue #256.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
add some screenshot or video to see you changes.

**Comment by sancharigandhi** [comment]
image
image

**Comment by Suchitra-Sahoo** [comment]
I had to revert back your PR because after your changes the contact part is not visible in navbar
image

**Comment by sancharigandhi** [comment]
Okay Ma'am, I am solving that issue as soon as possible.

**Pull request merged**
