### PR TITLE
Added login/register page and background animation for the page

### PR DESCRIPTION
**Pull request by Hemav009**
## Related Issue
#728 

## Description

Added login or register page using toggle feature on buttons.
And background image animation for page

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109607812/fcc0e311-9e37-4eda-a131-465351ad4ab7

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

check at this link:

https://hemav009.github.io/AgriLearnNetwork/

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
image
it is still showing the same

**Comment by Hemav009** [comment]
@Suchitra-Sahoo  this PR is for login page not for contact us section

**Comment by Suchitra-Sahoo** [comment]
create another PR

**Comment by Hemav009** [comment]
Sure

**Pull request merged**
