### PR TITLE
Added FAQ's Section and styled it with Navbar and Footbar

### PR DESCRIPTION
**Pull request by vinay-reddy31**
## Related Issue
Added and styled FAQ's Section along with Navbar and Footbar

## Description
Based on the three feedbacks from you I modified 

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
But in the attached screenshot i can't see the navbar as in homepage. Currently only FAQ is written. Also footer is absent. If you have added attach in screenshot.

**Comment by Suchitra-Sahoo** [comment]
Also please mention your issue number. I have asked you this in previous PRs also

**Comment by vinay-reddy31** [comment]
image

Now Please merge this. If any changes i will add it based on feedback. If you merge it it is easy to commit new changes

**Comment by Suchitra-Sahoo** [comment]
Why there is gap below the footer? Show the navbar too, You please add a video to show the entire FAQ page as it is getting difficult to again and again merge your PR and revert it due o some issue.

**Comment by Suchitra-Sahoo** [comment]
Tell me your issue number

**Comment by vinay-reddy31** [comment]
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/139357392/493851bd-cbae-41f6-9f5a-e19450e82c7a

Started Building Directly Without any issue Number

**Comment by Suchitra-Sahoo** [comment]
@vinay-reddy31 as a gssoc contributor you should be aware that you can't raise a PR before raising an issue and without getting it assigned. You will not get any points if you issue and PR are not linked.

**Comment by vinay-reddy31** [comment]
Thankyou for the feedback Iam raising an issue

**Pull request closed without merging**
