### PR TITLE
added search bar to the buy product page

### PR DESCRIPTION
**Pull request by nandani-goyal**
## Related Issue
#1057 

## Description

I have added the search bar and also the heading "Agroproducts" to the page.

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot 2024-07-06 134723
image

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/152094228/a6277f0a-2b77-4a21-b7aa-9116f1da5e1c

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
There is a humble request of considering this PR of level2.

### CODE REVIEW

**Comment by Suchitra-Sahoo** [comment]
While we search something the description of the card moves towards right of the card instead of bottom center so fix it. It should look like this 
image

**Comment by nandani-goyal** [comment]
Ok I will try to make the changes like this

**Comment by nandani-goyal** [comment]
I have resolved the issue please have a review.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/152094228/644e4f95-1654-43fb-9342-3d3c8d61fb9e

**Comment by Suchitra-Sahoo** [comment]
image
When the search is not able to produce any result the footer is moved up. Kindly fix it.

**Comment by nandani-goyal** [comment]
kindly see the new pull request raised which solves all the issue you commented and please add gssoc label.

**Pull request merged**
